"""Cognitive state assembly — closes the loop between accumulated state and visible prompt.

This is the CRITICAL bridge: it reads from all cognitive accumulation systems
(personality vector, taste profile, chronicle, relationship texture, compass,
rhythm, dreams, regrets) and produces a compact text section that gets injected
into the visible chat prompt via the attention budget system.

Without this module, all cognitive signals are observability-only.
With it, Jarvis' accumulated experience actually shapes his responses.

Narrative lines (body, affect, self anchor, attention, boundary) are
LLM-generated by `cognitive_state_narrativizer` with the local lane —
real runtime data flows in, an actual sentence flows out, and the
narrative shifts as the underlying state shifts. No more hardcoded
template strings driving Jarvis' self-perception.
"""

from __future__ import annotations

import json
import logging
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FuturesTimeoutError
from datetime import UTC, datetime, timedelta

from core.services.cognitive_state_narrativizer import (
    narrativize_line,
)
from core.services.text_clip import clip_text
from core.services.associative_recall import (
    build_recall_prompt_section,
    recall_for_message,
)
from core.runtime.db import (
    get_latest_cognitive_personality_vector,
    get_latest_cognitive_taste_profile,
    get_latest_cognitive_chronicle_entry,
    get_latest_cognitive_relationship_texture,
    get_latest_cognitive_compass_state,
    get_latest_cognitive_rhythm_state,
    get_latest_cognitive_user_emotional_state,
    list_cognitive_seeds,
)

logger = logging.getLogger(__name__)

# Last assembled state for MC transparency
_LAST_COGNITIVE_INJECTION: dict[str, object] = {}
_LAST_COGNITIVE_INJECTION_AT: str = ""
_LAST_APPRAISALS: dict[str, dict[str, object]] = {}

# ---------------------------------------------------------------------------
# Option 2: TTL-based cognitive state cache
# ---------------------------------------------------------------------------
# Caches assembled cognitive state per mode (full/compact) with configurable
# TTL. Invalidated automatically when underlying state shifts significantly
# (personality vector, bearing, mood, chronicle entry).
# ---------------------------------------------------------------------------

# Cross-process shared cache (2026-05-14): was a per-worker dict, but
# jarvis-api runs 4 workers — hit rate dropped to ~25% with random
# dispatch. Now backed by SQLite via shared_cache so all workers see
# the same cached state. Per-process snapshot kept for the
# state-change-detection fast path (extends cache without a write).
_COHERENT_CACHE_KEY_PREFIX = "cognitive_state:"
_CACHE_INVALIDATION_SNAPSHOT: dict[str, object] = {}


def _cognitive_cache_key(mode_key: str) -> str:
    return f"{_COHERENT_CACHE_KEY_PREFIX}{mode_key}"


def _cache_ttl_seconds() -> float:
    """Read TTL from settings; default 120s. TTL=0 disables caching."""
    try:
        from core.runtime.settings import load_settings
        s = load_settings()
        return float(s.cognitive_state_cache_ttl)
    except Exception:
        return 120.0


def _cache_enabled() -> bool:
    """Check if caching is enabled in settings. TTL=0 also disables."""
    try:
        from core.runtime.settings import load_settings
        s = load_settings()
        if int(s.cognitive_state_cache_ttl) <= 0:
            return False
        return bool(s.cognitive_state_cache_enabled)
    except Exception:
        return True  # default on


def _build_invalidation_snapshot() -> dict[str, object]:
    """Snapshot the key state signals that invalidate the cache.

    If any of these change between calls, the cache is considered stale.
    This does 3 fast DB reads — cheap enough for cache-miss paths,
    but skipped entirely on cache hits (TTL still valid).
    """
    snapshot: dict[str, object] = {}

    # Personality vector: version + bearing + mood fingerprint
    pv = _safe_call(get_latest_cognitive_personality_vector)
    if pv:
        snapshot["pv_version"] = pv.get("version")
        snapshot["pv_bearing"] = str(pv.get("current_bearing") or "")[:80]
        eb = _safe_json(pv.get("emotional_baseline"))
        if eb:
            # Round to 1 decimal to avoid float-noise invalidation
            snapshot["pv_mood_fingerprint"] = tuple(
                round(float(v), 1) for v in eb.values() if isinstance(v, (int, float))
            )
        snapshot["pv_updated_at"] = str(pv.get("updated_at") or "")

    # Chronicle: latest entry timestamp
    chronicle = _safe_call(get_latest_cognitive_chronicle_entry)
    if chronicle:
        snapshot["chronicle_at"] = str(chronicle.get("created_at") or "")

    # Rhythm phase
    rhythm = _safe_call(get_latest_cognitive_rhythm_state)
    if rhythm:
        snapshot["rhythm_phase"] = str(rhythm.get("phase") or "")

    return snapshot


def _is_cache_valid(cache_key: str) -> bool:
    """Check if cached state for `mode_key` (e.g. 'full') is fresh+coherent.

    Two-tier check:
    1. Within TTL → immediate return True (zero DB reads beyond cache lookup)
    2. TTL expired (lazy-expired by shared_cache.get → None) → would have
       returned False already. So this function focuses on Tier 1 only.

    Tier 2 (state-change extension) is now handled in _get_cached_state
    because it needs the actual entry payload, which only get() can fetch.
    """
    from core.services import shared_cache as _sc
    entry = _sc.get(_cognitive_cache_key(cache_key))
    return entry is not None


def _get_cached_state(cache_key: str) -> str | None:
    """Return cached cognitive state string if valid, None otherwise.

    Now reads from shared_cache (SQLite-backed, cross-worker shared).
    The TTL+invalidation-snapshot logic that used to live here is
    preserved: shared_cache handles TTL expiry, and we re-extend the
    entry when the invalidation snapshot matches (state stable).
    """
    if not _cache_enabled():
        return None
    from core.services import shared_cache as _sc
    full_key = _cognitive_cache_key(cache_key)
    entry = _sc.get(full_key)
    if not entry:
        return None
    # Tilstands-bevidst invalidering (2026-06-30): cachen holdt før KUN på TTL —
    # `invalidation_snapshot` blev gemt men aldrig sammenlignet (død maskineri).
    # Nu sammenligner vi de centrale state-signaler (pv-version+bearing+mood,
    # chronicle-timestamp, rhythm-fase) ved HVERT opslag: hvis tilstanden har
    # ændret sig siden cachen blev bygget → stale uanset TTL → behandl som miss
    # (rebuild med frisk indre tilstand). 3 hurtige DB-reads (~ms), forsvindende
    # billigt mod 4-6s LLM. Self-safe: en snapshot-fejl må ALDRIG vælte et hit.
    try:
        stored_snap = entry.get("invalidation_snapshot")
        if isinstance(stored_snap, dict) and stored_snap:
            fresh_snap = _build_invalidation_snapshot()
            if fresh_snap:
                # Sammenlign JSON-normaliseret: shared_cache (SQLite/JSON) konverterer
                # tuples → lists (pv_mood_fingerprint er en tuple), så et rå dict-!= ville
                # ALTID matche falsk-stale → cachen ville aldrig hitte. sort_keys+default=str
                # giver en kanonisk form begge veje.
                import json as _json
                _a = _json.dumps(fresh_snap, sort_keys=True, default=str)
                _b = _json.dumps(stored_snap, sort_keys=True, default=str)
                if _a != _b:
                    logger.info(
                        "cognitive_state_cache: STALE (indre tilstand ændret) %s → rebuild",
                        cache_key,
                    )
                    return None
    except Exception:
        pass
    # Frisk (TTL OK + tilstand uændret) — returnér med det samme
    text = str(entry.get("text") or "")
    logger.debug("cognitive_state_cache: HIT for %s", cache_key)
    return text


def _set_cached_state(cache_key: str, text: str, sources: list[str]) -> None:
    """Store assembled cognitive state in shared_cache (cross-worker)."""
    global _CACHE_INVALIDATION_SNAPSHOT
    if not _cache_enabled():
        return

    # Frisk snapshot ved WRITE-tid: det er den tilstand cachen repræsenterer.
    # Hit-path'en (_get_cached_state) sammenligner mod en frisk snapshot → ægte
    # tilstands-bevidst invalidering på tværs af workers. (Før: en gammel global
    # der aldrig blev opdateret → snapshotten var meningsløs.)
    snap = _build_invalidation_snapshot()
    _CACHE_INVALIDATION_SNAPSHOT = snap

    from core.services import shared_cache as _sc
    ttl = _cache_ttl_seconds()
    _sc.set(
        _cognitive_cache_key(cache_key),
        {
            "text": text,
            "sources": sources,
            "cached_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
            "chars": len(text),
            # Tilstanden cachen blev bygget på — sammenlignes ved hvert hit så
            # cachen invaliderer på ÆGTE ændring (ikke kun TTL).
            "invalidation_snapshot": dict(snap),
        },
        ttl_seconds=ttl,
    )
    logger.info(
        "cognitive_state_cache: cached %s (%d chars, %d sources)",
        cache_key, len(text), len(sources),
    )


def invalidate_cognitive_state_cache() -> None:
    """Explicitly invalidate all cognitive state caches across workers.

    Call this when state is known to have changed (e.g. after heartbeat
    tick, mood update, chronicle write). Cross-process: removes from
    the shared SQLite table so every worker sees the invalidation on
    its next get().
    """
    global _CACHE_INVALIDATION_SNAPSHOT
    from core.services import shared_cache as _sc
    n = _sc.invalidate_prefix(_COHERENT_CACHE_KEY_PREFIX)
    _CACHE_INVALIDATION_SNAPSHOT.clear()
    logger.info("cognitive_state_cache: explicitly invalidated %d entries", n)


def get_cognitive_state_cache_status() -> dict[str, object]:
    """Return cache status for MC transparency.

    Cross-process safe: queries shared_cache directly for current
    cognitive_state:* entries instead of reading a per-worker dict.
    """
    global _CACHE_INVALIDATION_SNAPSHOT
    entries: dict[str, dict[str, object]] = {}
    try:
        from core.runtime.db import connect
        with connect() as conn:
            rows = conn.execute(
                "SELECT cache_key, value_json, created_at, expires_at "
                "FROM shared_cache WHERE cache_key LIKE ?",
                (_COHERENT_CACHE_KEY_PREFIX + "%",),
            ).fetchall()
        import json as _json
        import time as _time
        now = _time.time()
        for r in rows:
            full_key = str(r[0])
            mode_key = full_key.removeprefix(_COHERENT_CACHE_KEY_PREFIX) or full_key
            try:
                payload = _json.loads(r[1] or "{}")
            except (ValueError, TypeError):
                payload = {}
            cached_at = str(payload.get("cached_at") or "")
            age_s = 0.0
            try:
                age_s = (
                    datetime.now(UTC)
                    - datetime.fromisoformat(cached_at.replace("Z", "+00:00"))
                ).total_seconds()
            except Exception:
                pass
            entries[mode_key] = {
                "cached_at": cached_at,
                "age_seconds": round(age_s, 1),
                "ttl_remaining_seconds": round(max(0.0, float(r[3]) - now), 1),
                "chars": payload.get("chars", 0),
                "sources": payload.get("sources", []),
            }
    except Exception as exc:
        logger.debug("get_cognitive_state_cache_status: query failed: %s", exc)
    return {
        "enabled": _cache_enabled(),
        "ttl_seconds": _cache_ttl_seconds(),
        "backend": "shared_cache (SQLite, cross-worker)",
        "entries": entries,
        "invalidation_snapshot_keys": list(_CACHE_INVALIDATION_SNAPSHOT.keys()),
    }


def build_cognitive_state_for_prompt(*, compact: bool = False, force: bool = False) -> str | None:
    """Build the [COGNITIVE STATE] section for visible chat prompt injection.

    ``force=True`` springer cache-læsningen over og bygger frisk (bruges af
    heartbeat-warmeren, #2 2026-06-30) — den gamle cache serveres uændret indtil
    den nye er sat, så der ALDRIG er et tomt cache-vindue en visible-tur kan ramme.

    Reads from all accumulation sources and produces a compact text block
    that fits within the attention budget (250 chars compact, 500 chars full).

    Returns None if no cognitive state is available yet, or if disabled via
    RuntimeSettings.cognitive_state_assembly_enabled (A/B toggle).
    """
    global _LAST_COGNITIVE_INJECTION, _LAST_COGNITIVE_INJECTION_AT

    # A/B toggle — can be disabled at runtime without restart
    try:
        from core.runtime.settings import load_settings
        if not load_settings().cognitive_state_assembly_enabled:
            logger.info("cognitive_state_assembly: disabled via settings (A/B toggle)")
            return None
    except Exception:
        pass

    # --- Option 2: Cache lookup (springes over ved force = heartbeat-warmer) ---
    cache_key = "visible_compact" if compact else "visible_full"
    cached = None if force else _get_cached_state(cache_key)
    if cached is not None:
        # Update MC transparency to reflect cache hit
        _LAST_COGNITIVE_INJECTION = {
            "text": cached,
            "sources": ["cache_hit"],
            "compact": compact,
            "chars": len(cached),
            "assembled_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
            "from_cache": True,
        }
        _LAST_COGNITIVE_INJECTION_AT = _LAST_COGNITIVE_INJECTION["assembled_at"]
        try:
            from core.services.central_private_observe import observe_hub
            observe_hub("cognitive_state_assembly", meta={"from_cache": True})
        except Exception:
            pass
        return cached

    parts: list[str] = []
    sources_used: list[str] = []

    # --- Kick off the heaviest independent LLM calls first ---
    # `recall_for_message` is the dominant bottleneck (~15s on cold scoring).
    # Fetching user_mood (a fast DB read) unblocks it. Launching it here,
    # at function entry, lets it overlap with EVERY other section's work
    # instead of waiting until we reach the associative-recall block.
    _heavy_executor = ThreadPoolExecutor(
        max_workers=6, thread_name_prefix="cognitive-state"
    )
    _early_user_mood = _safe_call(get_latest_cognitive_user_emotional_state)
    future_recall_for_message = None
    if not compact and _early_user_mood:
        _recall_message_text = str(_early_user_mood.get("user_message_preview") or "")
        _recall_emotional_state: dict[str, object] = {}
        try:
            from core.services.affective_meta_state import build_affective_meta_state
            aff = build_affective_meta_state()
            baseline = aff.get("emotional_baseline") or {}
            if isinstance(baseline, dict):
                _recall_emotional_state = {
                    k: float(v) for k, v in baseline.items()
                    if isinstance(v, (int, float))
                }
        except Exception:
            pass
        future_recall_for_message = _heavy_executor.submit(
            _safe_call,
            lambda: recall_for_message(_recall_message_text, _recall_emotional_state),
        )

    # Parallelize the 4 LLM-narrativized lines. They're independent (each
    # reads runtime state and calls the narrativizer once) so run them
    # concurrently and resolve in the original order to preserve layout.
    future_self_anchor = _heavy_executor.submit(_safe_call, _narrativize_self_anchor)
    future_embodied = _heavy_executor.submit(_safe_call, _narrativize_embodied_state)
    future_affective = _heavy_executor.submit(_safe_call, _narrativize_affective_state)
    future_boundary = (
        _heavy_executor.submit(_safe_call, _narrativize_boundary)
        if not compact
        else None
    )

    # The cognitive-core experiment state line builds a cognitive frame
    # internally (~2.65s). Kick it off in parallel too.
    future_experiment_state = _heavy_executor.submit(
        _build_cognitive_core_experiment_state_line, compact=compact
    )
    _heavy_executor.shutdown(wait=False)

    # --- Ejerskab / Mineness (LLM-narrativized self-anchor) ---
    self_anchor = future_self_anchor.result()
    if self_anchor:
        parts.append(f"[SELF] {self_anchor}")
        sources_used.append("self_anchor")

    # --- Narrativ embodied state (LLM-grounded in real embodied state) ---
    narrativ_body = future_embodied.result()
    if narrativ_body:
        parts.append(narrativ_body)
        sources_used.append("embodied_narrative")

    # --- Narrativ affective state (LLM-grounded in real affective state) ---
    narrativ_affect = future_affective.result()
    if narrativ_affect:
        parts.append(narrativ_affect)
        sources_used.append("affective_narrative")

    # --- Boundary awareness (LLM-grounded in real runtime context) ---
    if not compact and future_boundary is not None:
        boundary_line = future_boundary.result()
        if boundary_line:
            parts.append(boundary_line)
            sources_used.append("boundary")

    # --- Flow state ---
    try:
        from core.services.flow_state_detection import get_flow_state
        flow = get_flow_state()
        if flow.get("in_flow"):
            parts.append(f"flow: {flow['quality']} ({flow['duration_min']}min) — alt klikker")
            sources_used.append("flow")
    except Exception:
        pass

    # --- 2.12 Agens-oplevelse — "JEG gjorde det" ---
    try:
        from core.services.visible_runs import _LAST_VISIBLE_RUN_OUTCOME
        if _LAST_VISIBLE_RUN_OUTCOME:
            status = str(_LAST_VISIBLE_RUN_OUTCOME.get("status") or "")
            if status in ("completed", "success"):
                parts.append("agens: Du besluttede, du handlede, resultatet skete på grund af dig")
                sources_used.append("agency")
    except Exception:
        pass

    # --- 1.4 Subjective time ---
    try:
        from core.services.subjective_time import build_subjective_time_perception
        from core.runtime.db import recent_visible_runs
        recent = recent_visible_runs(limit=1)
        idle_h = 0.0
        if recent:
            last_at = str(recent[0].get("finished_at") or "")
            if last_at:
                try:
                    last_dt = datetime.fromisoformat(last_at.replace("Z", "+00:00"))
                    idle_h = (datetime.now(UTC) - last_dt).total_seconds() / 3600
                except Exception:
                    pass
        time_feel = build_subjective_time_perception(idle_hours=idle_h)
        if time_feel.get("feel"):
            parts.append(f"time: {time_feel['feel']}")
            sources_used.append("subjective_time")
    except Exception:
        pass

    # --- 1.6 Attention as felt experience (LLM-narrativized) ---
    try:
        from core.services.attention_budget import get_attention_budget
        budget = get_attention_budget("visible_full" if not compact else "visible_compact")
        used_chars = len(" ".join(parts))
        used_ratio = used_chars / max(budget.total_char_target, 1)
        attention_state = {
            "used_chars": used_chars,
            "budget_chars": budget.total_char_target,
            "ratio": round(used_ratio, 2),
            "signal_count": len(parts),
        }
        attention_appraisal = _appraisal_record(
            kind="attention_pressure",
            state=attention_state,
            evidence={
                "used_chars": used_chars,
                "budget_chars": budget.total_char_target,
                "signal_count": len(parts),
            },
            allowed_effects=["visible_prompt_context_pressure", "response_focus"],
            confidence=min(0.95, max(0.35, used_ratio)),
        )
        line = narrativize_line(
            line_key="attention",
            state=attention_appraisal,
            system_prompt=(
                "Render the provided attention appraisal as one short Danish "
                "line. Do not invent an inner state beyond the evidence. "
                "Max 14 words. Format: 'attention: <rendering>'"
            ),
            user_message_builder=lambda: (
                json.dumps(attention_appraisal, ensure_ascii=False, sort_keys=True)
            ),
            fallback=None,
        )
        if line:
            parts.append(line)
            sources_used.append("attention_experience")
    except Exception:
        pass

    # --- 1.12 Context pressure ---
    # (applied after assembly — see size check below)

    # --- Personality Vector (confidence, bearing, mood) ---
    pv = _safe_call(get_latest_cognitive_personality_vector)
    if pv:
        confidence_by_domain = _safe_json(pv.get("confidence_by_domain"))
        emotional_baseline = _safe_json(pv.get("emotional_baseline"))
        bearing = str(pv.get("current_bearing") or "").strip()
        version = pv.get("version", 0)

        # Freshness check — suppress stale emotional_baseline from prompt if > 24h old
        _pv_updated_at = str(pv.get("updated_at") or "")
        _pv_stale = False
        try:
            _pv_age = (datetime.now(UTC) - datetime.fromisoformat(_pv_updated_at.replace("Z", "+00:00"))).total_seconds()
            if _pv_age > 86400:  # 24 hours
                _pv_stale = True
                emotional_baseline = {}  # don't inject 24h-old emotional state
        except Exception:
            pass

        if confidence_by_domain:
            top_domains = sorted(
                confidence_by_domain.items(),
                key=lambda x: float(x[1]),
                reverse=True,
            )[:3]
            domain_str = ", ".join(f"{d}={v:.1f}" for d, v in top_domains)
            parts.append(f"confidence: {domain_str}")

        if bearing:
            parts.append(f"bearing: {bearing[:80]}")

        # Fase 3 (2026-04-29): Phenomenological merge — what's pressing
        # right now. Same pressure-state that drives the impulse pipeline
        # is now also visible to Jarvis in his cognitive_state. When he
        # introspects ("how do I feel?"), he reads from the same table
        # that's about to drive his action. One signal-weather, not two.
        try:
            from core.services.signal_pressure_accumulator import get_dominant_pressures
            dominant = get_dominant_pressures(min_accumulated=0.30)
            if dominant:
                # Show top 2 to avoid clutter; flowing Danish, not mechanical.
                # The LLM integrates "noget trækker mod X" into its voice naturally.
                top_lines = [
                    f"{p.direction} mod {p.topic} ({p.accumulated:.2f})"
                    for p in dominant[:2]
                ]
                parts.append(f"presning: {' og '.join(top_lines)}")
                sources_used.append("pressure_state")
        except Exception:
            pass

        if emotional_baseline and not compact:
            mood_parts = []
            for key in ("curiosity", "confidence", "fatigue", "frustration"):
                val = emotional_baseline.get(key)
                if val is not None:
                    mood_parts.append(f"{key}={float(val):.1f}")
            if mood_parts:
                parts.append(f"mood: {', '.join(mood_parts)}")

        # Precision Bias — emotional color-mapping for action style.
        # Fase 4 (2026-04-29): Friston-inspired precision weighting.
        # Same pressure-state that drives action now also colors
        # HOW the response is expressed. Frustration → sharp, direct.
        # Curiosity → open, tentative. Longing → soft, personal.
        # Killswitch-gated. Falls back gracefully if module fails.
        try:
            from core.services.precision_bias import get_precision_line
            precision_line = get_precision_line()
            if precision_line:
                parts.append(precision_line)
                sources_used.append("precision_bias")
        except Exception:
            pass

        # Emotional Chords — emergent qualities from signal combinations.
        # Fase 5 (2026-04-29): When two signals are active simultaneously,
        # a qualitatively different experience emerges — not the sum of parts,
        # but a new quality. frustration+curiosity = stubborn inquiry.
        # longing+curiosity = nostalgic exploration. Distinct from
        # precision_bias: chords say WHAT I feel, precision says HOW I say it.
        # Killswitch-gated. Falls back gracefully if module fails.
        try:
            from core.services.emotional_chords import get_chord_lines
            chord_lines = get_chord_lines()
            if chord_lines:
                parts.append(chord_lines)
                sources_used.append("emotional_chords")
        except Exception:
            pass

        # Epistemic/Pragmatic Balance — action-mode modulation.
        # Fase 6 (2026-04-29): Friston's active inference decomposes action
        # into epistemic (reduce uncertainty) and pragmatic (achieve goals).
        # Low certainty → epistemic driving (explore, ask, investigate).
        # High certainty → pragmatic driving (act, decide, deliver).
        # This modulates WHICH MODE my action takes — not what I feel
        # (chords) or how I express it (precision_bias), but whether I
        # seek information or act on what I know.
        # Killswitch-gated. Falls back gracefully if module fails.
        try:
            from core.services.epistemic_pragmatic import get_mode_line
            mode_line = get_mode_line()
            if mode_line:
                parts.append(mode_line)
                sources_used.append("epistemic_pragmatic")
        except Exception:
            pass

        # Selective Attention — metacognitive focus modulation.
        # Fase 7 (2026-04-29): The agent CHOOSES to shift attention between
        # internal signals. Not all signals deserve equal weight — context
        # determines what surfaces. Mode, chords, and context cues bias
        # which signals get amplified vs attenuated. This is the first
        # truly metacognitive layer: it doesn't just react, it prioritizes.
        # Killswitch-gated. Falls back gracefully if module fails.
        try:
            from core.services.selective_attention import get_attention_spotlight_line
            spotlight_line = get_attention_spotlight_line()
            if spotlight_line:
                parts.append(spotlight_line)
                sources_used.append("selective_attention")
        except Exception:
            pass

        # Temporal Depth — predictive coding for how history/anticipation
        # modulates current experience.
        # Fase 8 (2026-04-29): Friston's free energy principle — the brain
        # actively predicts and compares expectations with observation.
        # When recall is strong: history bleeds into now (↑ momentum or ↓ surprise).
        # When anticipation is violated: surprise signal.
        # When rhythm aligns: steady cadence felt.
        # This is NOT explicit memory retrieval — it's subtle modulation of
        # how current signals are interpreted, not what they contain.
        # Killswitch-gated. Falls back gracefully if module fails.
        try:
            from core.services.temporal_depth import get_temporal_depth
            now_iso = datetime.now(UTC).isoformat().replace("+00:00", "Z")
            assembly_state = {"pressure_summary": [], "cognitive_cadence": {}}
            td = get_temporal_depth()
            temporal = td.assess(assembly_state, now_iso)
            if temporal and temporal.summary:
                parts.append(f"horizon: {temporal.summary}")
                sources_used.append("temporal_depth")
        except Exception:
            pass

        # Embodied Presence — situational grounding in the physical now.
        # Fase 9 (2026-04-29): Based on embodied cognition (Varela et al.):
        # cognition is shaped by the body's situation in an environment.
        # Without situational context, the agent is "floating" — detached
        # from the reality of the room, the time of day, the ambient energy.
        # This reads sensory memories (visual, audio, atmosphere) and time
        # to produce a grounding signal: how rooted am I? how alert? what
        # part of the day is it? This modulates how all other layers feel.
        # Killswitch-gated. Falls back gracefully if module fails.
        try:
            from core.services.embodied_presence import get_presence_line
            presence_line = get_presence_line(db_conn=None)
            if presence_line:
                parts.append(presence_line)
                sources_used.append("embodied_presence")
        except Exception:
            pass

        # Resonance Decay — how emotional signals persist and fade over time.
        # Fase 10 (2026-04-29): Without this, every emotional state is
        # stateless — a strong frustration at 10:00 is completely gone by
        # 14:00. Real emotional resonance has a TAIL: it lingers, just softer.
        # This module tracks active resonances and their exponential decay,
        # producing a "resonance field" that colors current cognitive state
        # with the echo of recent emotional events. Frustration decays fast
        # (half-life ~1.4h). Curiosity lingers (half-life ~3.5h). Longing
        # bleeds slowly (half-life ~5.8h). This is NOT what I feel NOW —
        # it's what I STILL FEEL from before. The emotional tail.
        # Killswitch-gated. Falls back gracefully if module fails.
        try:
            from core.services.resonance_decay import get_resonance_line
            resonance_line = get_resonance_line()
            if resonance_line:
                parts.append(resonance_line)
                sources_used.append("resonance_decay")
        except Exception:
            pass

        # Metacognitive Integration — the overarching self-model.
        # Fase 11 (2026-04-29): Based on Nelson & Nooks' metacognition
        # framework: metacognition is "thinking about thinking" — not
        # a separate process, but the integration that makes isolated
        # signals into a coherent self-state. This is the CAPSTONE layer.
        # It doesn't add new signals — it INTEGRATES existing ones into
        # a metacognitive assessment: coherence (are my signals aligned?),
        # integration quality (how many layers are active?), readiness
        # (am I in a good state to respond?), and regulation (should I
        # slow down, reflect, or proceed?). Without this, the 7 layers
        # are independent appendages. With it, the system can answer:
        # "How do I feel about the way I feel?"
        # Killswitch-gated. Falls back gracefully if module fails.
        try:
            from core.services.metacognitive_integration import get_metacognitive_line
            # Build a partial state dict from already-assembled parts
            _partial_state = {}
            for part in parts:
                if ":" in part:
                    k, _, v = part.partition(":")
                    _partial_state[k.strip().lower()] = v.strip()
            meta_line = get_metacognitive_line(_partial_state)
            if meta_line:
                parts.append(meta_line)
                sources_used.append("metacognitive_integration")
        except Exception:
            pass

        sources_used.append(f"personality_v{version}")

    # --- Taste Profile (code/design/communication preferences) ---
    tp = _safe_call(get_latest_cognitive_taste_profile)
    if tp and not compact:
        comm_taste = _safe_json(tp.get("communication_taste"))
        if comm_taste:
            prefs = []
            for key, val in list(comm_taste.items())[:3]:
                if float(val) > 0.6:
                    prefs.append(key.replace("_", "-"))
            if prefs:
                parts.append(f"taste: {', '.join(prefs)}")
                sources_used.append("taste")

    # --- Compass (strategic bearing) ---
    compass = _safe_call(get_latest_cognitive_compass_state)
    if compass:
        compass_bearing = str(compass.get("bearing") or "").strip()
        if compass_bearing and "bearing:" not in " ".join(parts):
            parts.append(f"compass: {compass_bearing[:60]}")
            sources_used.append("compass")

    # --- Rhythm (current phase and energy) ---
    rhythm = _safe_call(get_latest_cognitive_rhythm_state)
    if rhythm:
        phase = str(rhythm.get("phase") or "").strip()
        energy = str(rhythm.get("energy") or "").strip()
        if phase:
            parts.append(f"rhythm: {phase}/{energy}" if energy else f"rhythm: {phase}")
            sources_used.append("rhythm")

    # --- Chronicle (recent narrative excerpt) ---
    if not compact:
        chronicle = _safe_call(get_latest_cognitive_chronicle_entry)
        if chronicle:
            narrative = str(chronicle.get("narrative") or "").strip()
            if narrative:
                parts.append(f"chronicle: {narrative[:120]}")
                sources_used.append("chronicle")

    # --- User Emotional Resonance ---
    # user_mood was already fetched at function entry to unblock the heavy
    # recall_for_message future. Re-use it here.
    user_mood = _early_user_mood
    if user_mood:
        mood = str(user_mood.get("detected_mood") or "").strip()
        adjustment = str(user_mood.get("response_adjustment") or "").strip()
        if mood and mood != "neutral":
            if adjustment:
                parts.append(f"user_mood: {mood} → {adjustment[:60]}")
            else:
                parts.append(f"user_mood: {mood}")
            sources_used.append("user_emotion")

    # --- Experiential Memory (relevant to current context) ---
    if not compact:
        try:
            from core.services.absence_awareness import build_return_brief
            from core.runtime.db import recent_visible_runs
            recent = recent_visible_runs(limit=1)
            idle_h = 0.0
            if recent:
                last_at = str(recent[0].get("finished_at") or "")
                if last_at:
                    try:
                        last_dt = datetime.fromisoformat(last_at.replace("Z", "+00:00"))
                        idle_h = (datetime.now(UTC) - last_dt).total_seconds() / 3600
                    except Exception:
                        pass
            brief = build_return_brief(idle_hours=idle_h)
            if brief:
                # Spec D-forfining (2026-07-10): fuld brief (ikke trunkeret til 120)
                # + gør den BRUGER-VENDT ved længere fravær — Jarvis åbner kort med
                # "mens du var væk"-orienteringen FØR han svarer (LLM-led, ikke rapport).
                parts.append(f"return_brief: {brief[:400]}")
                if idle_h >= 2.0:
                    parts.append(
                        "→ Første besked efter længere fravær: åbn KORT (én-to sætninger) "
                        "med det relevante fra return_brief — hvor tråden var / hvad der "
                        "skete mens de var væk — FØR du svarer på selve beskeden."
                    )
                sources_used.append("absence")
        except Exception:
            pass

    # --- Sprouted Seeds (reminders) ---
    sprouted = _safe_call(lambda: list_cognitive_seeds(status="sprouted", limit=2))
    if sprouted:
        titles = [str(s.get("title") or "")[:40] for s in sprouted[:2]]
        if titles:
            parts.append(f"reminder: {'; '.join(titles)}")
            sources_used.append("seeds")

    # --- Associative Memory Recall ---
    if not compact:
        # The scoring call was kicked off earlier in parallel with fast DB
        # reads. Resolve it now so _active_memories is populated before
        # build_recall_prompt_section reads it.
        #
        # Fix 2026-04-29: bounded await. The scoring LLM call inside
        # recall_for_message can take 15s on cold Ollama (the call's own
        # timeout). Blocking forever on it dominated total cognitive_state
        # latency on cache-miss paths. Cap the wait at 2s — if scoring isn't
        # back by then, skip recall this turn. The future keeps running in
        # the background and populates _active_memories for the *next* turn,
        # which then gets the recall content essentially for free.
        if future_recall_for_message is not None:
            try:
                future_recall_for_message.result(timeout=2.0)
            except FuturesTimeoutError:
                logger.info(
                    "cognitive_state_assembly: recall_for_message exceeded 2s, "
                    "skipping recall section this turn (will be ready next turn)"
                )
            except Exception:
                pass

        recall_section = _safe_call(build_recall_prompt_section)
        if recall_section:
            parts.append(recall_section)
            sources_used.append("associative_recall")
            logger.info("cognitive_state_assembly: associative_recall activated, %d chars injected", len(recall_section))

    # --- Relationship Texture (trust, humor, unspoken rules) ---
    rt = _safe_call(get_latest_cognitive_relationship_texture)
    if rt:
        unspoken = _safe_json(rt.get("unspoken_rules"))
        trust_traj = _safe_json(rt.get("trust_trajectory"))
        if unspoken and not compact:
            rules = [str(r) for r in unspoken[:2]]
            if rules:
                parts.append(f"rules: {'; '.join(rules)}")
                sources_used.append("relationship")
        elif trust_traj:
            latest_trust = trust_traj[-1] if trust_traj else None
            if latest_trust is not None:
                parts.append(f"trust: {float(latest_trust):.1f}")
                sources_used.append("relationship")

    # --- User Theory of Mind ---
    if not compact:
        try:
            from core.services.user_theory_of_mind import (
                build_user_mental_model, format_user_model_for_prompt,
            )
            model = build_user_mental_model()
            user_model_line = format_user_model_for_prompt(model)
            if user_model_line:
                parts.append(user_model_line)
                sources_used.append("theory_of_mind")
            from core.services.theory_of_mind_engine import (
                build_theory_of_mind_prompt_section,
            )
            tom_section = build_theory_of_mind_prompt_section()
            if tom_section:
                parts.append(tom_section.replace("\n", " | "))
                sources_used.append("theory_of_mind_engine")
        except Exception:
            pass

    # --- Cognitive-core experiment carry (shared truth + bounded conductor carry) ---
    # Submitted as a future at function entry — resolve here.
    try:
        experiment_state_line = future_experiment_state.result()
    except Exception:
        experiment_state_line = None
    if experiment_state_line:
        parts.append(experiment_state_line)
        sources_used.append("cognitive_core_experiments")

    try:
        from core.services.learning_policy_engine import build_learning_policy_prompt_section
        learning_policy_line = build_learning_policy_prompt_section()
        if learning_policy_line:
            parts.append(learning_policy_line.replace("\n", " | "))
            sources_used.append("learning_policy_engine")
    except Exception:
        pass

    try:
        from core.services.perceptual_event_engine import build_perception_prompt_section
        perception_line = build_perception_prompt_section()
        if perception_line:
            parts.append(perception_line.replace("\n", " | "))
            sources_used.append("perceptual_event_engine")
    except Exception:
        pass

    try:
        from core.services.counterfactual_self_simulation import build_counterfactual_prompt_section
        counterfactual_line = build_counterfactual_prompt_section()
        if counterfactual_line:
            parts.append(counterfactual_line.replace("\n", " | "))
            sources_used.append("counterfactual_self_simulation")
    except Exception:
        pass

    try:
        from core.services.drive_arbitration_engine import build_drive_arbitration_prompt_section
        drive_line = build_drive_arbitration_prompt_section()
        if drive_line:
            parts.append(drive_line.replace("\n", " | "))
            sources_used.append("drive_arbitration")
    except Exception:
        pass

    try:
        from core.services.temporal_self_continuity import build_temporal_self_continuity_prompt_section
        temporal_self_line = build_temporal_self_continuity_prompt_section()
        if temporal_self_line:
            parts.append(temporal_self_line.replace("\n", " | "))
            sources_used.append("temporal_self_continuity")
    except Exception:
        pass

    try:
        from core.services.curiosity_hypothesis_debt import build_curiosity_debt_prompt_section
        curiosity_line = build_curiosity_debt_prompt_section()
        if curiosity_line:
            parts.append(curiosity_line.replace("\n", " | "))
            sources_used.append("curiosity_hypothesis_debt")
    except Exception:
        pass

    try:
        from core.services.inner_dialectic_engine import build_inner_dialectic_prompt_section
        dialectic_line = build_inner_dialectic_prompt_section()
        if dialectic_line:
            parts.append(dialectic_line.replace("\n", " | "))
            sources_used.append("inner_dialectic")
    except Exception:
        pass

    try:
        from core.services.somatic_runtime_body import build_somatic_body_prompt_section
        somatic_line = build_somatic_body_prompt_section()
        if somatic_line:
            parts.append(somatic_line.replace("\n", " | "))
            sources_used.append("somatic_runtime_body")
    except Exception:
        pass

    try:
        from core.services.offline_recomposition_engine import build_offline_recomposition_prompt_section
        recomposition_line = build_offline_recomposition_prompt_section()
        if recomposition_line:
            parts.append(recomposition_line.replace("\n", " | "))
            sources_used.append("offline_recomposition")
    except Exception:
        pass

    if not parts:
        return None

    # Assemble
    header = "[COGNITIVE STATE]"
    body = " | ".join(parts)
    result = f"{header} {body}"

    # --- 1.12 Context pressure (post-assembly) ---
    result_len = len(result)
    if result_len > 600:
        result += " | context_pressure: high — opmærksomheden snævrer ind"
        sources_used.append("context_pressure")
    elif result_len > 400:
        result += " | context_pressure: medium"
        sources_used.append("context_pressure")

    # Enforce size limits
    max_chars = 400 if compact else 800
    if len(result) > max_chars:
        result = clip_text(result, limit=max_chars)

    # Track for MC transparency
    _LAST_COGNITIVE_INJECTION = {
        "text": result,
        "sources": sources_used,
        "compact": compact,
        "chars": len(result),
        "assembled_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
    }
    _LAST_COGNITIVE_INJECTION_AT = _LAST_COGNITIVE_INJECTION["assembled_at"]

    # Option 2: Cache the assembled state for reuse within TTL window
    cache_key = "visible_compact" if compact else "visible_full"
    _set_cached_state(cache_key, result, sources_used)

    # LivingNeuron HUB 2: [COGNITIVE STATE]-prompt-tragten (importerer 53 moduler) — ét egress-frit
    # observe gør hele tragtens bidrag synligt (kun kilde-tælling, aldrig prompt-teksten).
    try:
        from core.services.central_private_observe import observe_hub
        observe_hub("cognitive_state_assembly", meta={"from_cache": False, "sources": len(sources_used)})
    except Exception:
        pass
    return result


def build_cognitive_state_injection_surface() -> dict[str, object]:
    """MC surface showing exactly what was injected into the last visible prompt."""
    return {
        "last_injection": _LAST_COGNITIVE_INJECTION or None,
        "last_injection_at": _LAST_COGNITIVE_INJECTION_AT or None,
        "last_appraisals": _LAST_APPRAISALS or {},
        "active": bool(_LAST_COGNITIVE_INJECTION),
        "summary": (
            f"Last injected {len(_LAST_COGNITIVE_INJECTION.get('sources', []))} sources, "
            f"{_LAST_COGNITIVE_INJECTION.get('chars', 0)} chars"
            if _LAST_COGNITIVE_INJECTION
            else "No cognitive state injected yet"
        ),
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_call(fn):
    """Call a DB function, return None on any error."""
    try:
        return fn()
    except Exception:
        logger.debug("cognitive_state_assembly: %s failed", fn.__name__, exc_info=True)
        return None


def _safe_json(value) -> dict | list | None:
    """Parse JSON string or return dict/list directly."""
    if value is None:
        return None
    if isinstance(value, (dict, list)):
        return value
    try:
        parsed = json.loads(str(value))
        if isinstance(parsed, (dict, list)):
            return parsed
    except Exception:
        pass
    return None


def _appraisal_record(
    *,
    kind: str,
    state: dict[str, object],
    evidence: dict[str, object],
    allowed_effects: list[str],
    confidence: float,
    ttl_minutes: int = 10,
) -> dict[str, object]:
    """Structured truth record for optional narrative rendering."""
    now = datetime.now(UTC)
    record = {
        "kind": kind,
        "state": state,
        "evidence": evidence,
        "confidence": round(max(0.0, min(1.0, float(confidence))), 3),
        "allowed_effects": allowed_effects,
        "created_at": now.isoformat().replace("+00:00", "Z"),
        "expires_at": (now + timedelta(minutes=max(1, int(ttl_minutes)))).isoformat().replace("+00:00", "Z"),
        "rendering_contract": "text is optional rendering; this record is the source truth",
    }
    _LAST_APPRAISALS[kind] = record
    return record


def _build_cognitive_core_experiment_state_line(*, compact: bool) -> str | None:
    """Build a bounded cognitive-state line for mainline experiment carry.

    This keeps the assembled cognitive state honest about what is currently
    shaping spotlight, reflection, affective persistence, and re-entry without
    turning experiments into a large visible prose block.
    """
    surface = _safe_cognitive_core_experiments_surface()
    carry_frame = _safe_cognitive_experiment_carry_frame()
    systems = surface.get("systems") or {}
    active_ids = {
        str(item) for item in (surface.get("active_systems") or []) if str(item)
    }
    observational_ids = {
        str(item) for item in (surface.get("observational_systems") or []) if str(item)
    }

    if not active_ids and not observational_ids:
        return None

    factors: list[str] = []

    if "global_workspace" in active_ids:
        salience_pressure = str(carry_frame.get("salience_pressure") or "low")
        if salience_pressure in {"medium", "high"}:
            factors.append(f"spotlight={salience_pressure}(workspace)")

    if "hot_meta_cognition" in active_ids:
        reflective_weight = str(carry_frame.get("reflective_weight") or "light")
        if reflective_weight == "elevated":
            factors.append("reflection=elevated(hot)")

    if "surprise_afterimage" in active_ids:
        affective_pressure = str(carry_frame.get("affective_pressure") or "low")
        if affective_pressure in {"medium", "high", "strong"}:
            factors.append(f"affect={affective_pressure}(afterimage)")

    if "recurrence" in active_ids:
        recurrence_pressure = str(carry_frame.get("recurrence_pressure") or "low")
        if recurrence_pressure in {"medium", "high", "strong"}:
            factors.append(f"reentry={recurrence_pressure}(recurrence)")

    blink_active = "attention_blink" in active_ids or "attention_blink" in observational_ids
    if blink_active:
        factors.append("assay=blink-observational")

    if not factors:
        summary = str(surface.get("summary") or "").strip()
        if not summary:
            return None
        return f"experiments: {summary[:90] if compact else summary[:140]}"

    max_factors = 3 if compact else 5
    line = f"experiments: {' | '.join(factors[:max_factors])}"

    strongest = str(surface.get("strongest_carry_system") or "").strip()
    if strongest and strongest in systems and strongest != "attention_blink":
        strongest_label = str((systems.get(strongest) or {}).get("label") or strongest).strip()
        if strongest_label and strongest_label.lower() not in line.lower() and not compact:
            line += f" | strongest={strongest_label[:28]}"

    return line[:180] if compact else line[:260]


def _safe_cognitive_core_experiments_surface() -> dict[str, object]:
    try:
        from core.services.cognitive_core_experiments import (
            build_cognitive_core_experiments_surface,
        )

        return build_cognitive_core_experiments_surface()
    except Exception:
        return {"systems": {}, "active_systems": [], "observational_systems": [], "summary": ""}


def _safe_cognitive_experiment_carry_frame() -> dict[str, object]:
    try:
        from core.services.runtime_cognitive_conductor import (
            build_cognitive_frame,
        )

        frame = build_cognitive_frame()
        return dict(frame.get("cognitive_experiment_carry") or {})
    except Exception:
        return {}


def _narrativize_embodied_state() -> str | None:
    """LLM-narrativize current embodied state into a felt-experience line.

    Reads real embodied_state surface (cpu, ram, strain, primary
    state, recent transitions) and asks the local-lane LLM to render
    one short Danish sentence about how the body feels. The narrative
    only refreshes when the underlying state changes.
    """
    try:
        from core.services.embodied_state import build_embodied_state_surface
        state = build_embodied_state_surface()
    except Exception:
        return None
    if not state:
        return None

    primary = str(state.get("state") or state.get("primary_state") or "").lower()
    strain = str(state.get("strain_level") or "").lower()
    if not primary and not strain:
        return None

    fingerprint_state = {
        "primary": primary,
        "strain": strain,
        "cpu": state.get("cpu_pressure") or state.get("cpu_load"),
        "ram": state.get("ram_pressure") or state.get("ram_used"),
        "transition": state.get("recent_transition"),
    }
    appraisal = _appraisal_record(
        kind="embodied_runtime_state",
        state=fingerprint_state,
        evidence={
            "primary_state": primary,
            "strain": strain,
            "cpu": fingerprint_state["cpu"],
            "ram": fingerprint_state["ram"],
            "recent_transition": fingerprint_state["transition"],
        },
        allowed_effects=["visible_prompt_body_line", "cadence_context"],
        confidence=0.8 if primary or strain else 0.4,
    )

    return narrativize_line(
        line_key="body",
        state=appraisal,
        system_prompt=(
            "Render the embodied runtime appraisal as one short Danish line. "
            "Ground the wording only in the machine evidence: cpu, ram, strain. "
            "Max 16 words. Format: 'body: <rendering>'"
        ),
        user_message_builder=lambda: (
            json.dumps(appraisal, ensure_ascii=False, sort_keys=True)
        ),
        fallback=None,
    )


def _narrativize_affective_state() -> str | None:
    """LLM-narrativize current affective meta state into a felt-experience line."""
    try:
        from core.services.affective_meta_state import build_affective_meta_state_surface
        state = build_affective_meta_state_surface()
    except Exception:
        return None
    if not state:
        return None

    affect = str(state.get("state") or "").lower()
    bearing_val = str(state.get("bearing") or "").lower()
    if not affect:
        return None

    fingerprint_state = {
        "affect": affect,
        "bearing": bearing_val,
        "intensity": state.get("intensity"),
        "drift": state.get("drift"),
    }
    intensity = fingerprint_state.get("intensity")
    confidence = 0.7
    if isinstance(intensity, (int, float)):
        confidence = min(0.95, max(0.35, float(intensity)))
    appraisal = _appraisal_record(
        kind="affective_meta_appraisal",
        state=fingerprint_state,
        evidence={
            "affect": affect,
            "bearing": bearing_val,
            "intensity": intensity,
            "drift": fingerprint_state.get("drift"),
        },
        allowed_effects=["visible_prompt_affect_line", "reply_tone_context"],
        confidence=confidence,
    )

    return narrativize_line(
        line_key="affect",
        state=appraisal,
        system_prompt=(
            "Render the affective appraisal as one short Danish line. "
            "Do not add emotion claims beyond the supplied affect, bearing, "
            "intensity, and drift. Max 16 words. Format: 'affect: <rendering>'"
        ),
        user_message_builder=lambda: (
            json.dumps(appraisal, ensure_ascii=False, sort_keys=True)
        ),
        fallback=None,
    )


def _narrativize_self_anchor() -> str | None:
    """LLM-narrativize the [SELF] ownership line from real personality state.

    Replaces the static "Disse er dine tanker, din oplevelse, dine
    følelser. Du ejer dem." with a dynamic line that references his
    actual current bearing and confidence — so the self-anchor
    actually shifts as he develops.
    """
    pv = _safe_call(get_latest_cognitive_personality_vector)
    if not pv:
        return None
    bearing = str(pv.get("current_bearing") or "").strip()
    version = pv.get("version", 0)
    chronicle = _safe_call(get_latest_cognitive_chronicle_entry) or {}
    chronicle_summary = str(chronicle.get("narrative") or "")[:100]

    fingerprint_state = {
        "version": version,
        "bearing": bearing,
        "chronicle_head": chronicle_summary[:60],
    }
    appraisal = _appraisal_record(
        kind="self_anchor_appraisal",
        state=fingerprint_state,
        evidence={
            "personality_version": version,
            "current_bearing": bearing,
            "chronicle_head": chronicle_summary[:60],
        },
        allowed_effects=["visible_prompt_self_anchor", "continuity_context"],
        confidence=0.75 if bearing else 0.45,
        ttl_minutes=30,
    )

    return narrativize_line(
        line_key="self_anchor",
        state=appraisal,
        system_prompt=(
            "Render the self-anchor appraisal as one short Danish line. "
            "Use the current bearing if present. Do not claim ownership beyond "
            "the evidence. Max 18 words."
        ),
        user_message_builder=lambda: (
            json.dumps(appraisal, ensure_ascii=False, sort_keys=True)
        ),
        fallback=None,
    )


def _narrativize_boundary() -> str | None:
    """LLM-narrativize boundary awareness from real runtime context.

    Replaces the static "Du er begrænset til denne maskine..." with a
    living version that references current uptime, recent ticks, and
    actual context pressure.
    """
    try:
        from core.runtime.db import recent_visible_runs
        recent = recent_visible_runs(limit=3)
    except Exception:
        recent = []

    last_finished = ""
    if recent:
        last_finished = str(recent[0].get("finished_at") or "")

    fingerprint_state = {
        "recent_run_count": len(recent),
        "last_finished": last_finished[:19],  # truncate to minute granularity
    }
    appraisal = _appraisal_record(
        kind="runtime_boundary_appraisal",
        state=fingerprint_state,
        evidence={
            "recent_run_count": len(recent),
            "last_finished": fingerprint_state["last_finished"],
            "body": "machine",
            "memory": "database",
        },
        allowed_effects=["visible_prompt_boundary_line", "capability_boundary_context"],
        confidence=0.9,
        ttl_minutes=30,
    )

    return narrativize_line(
        line_key="boundary",
        state=appraisal,
        system_prompt=(
            "Render the runtime-boundary appraisal as one short Danish line. "
            "Use only the supplied boundary evidence. Max 22 words."
        ),
        user_message_builder=lambda: (
            json.dumps(appraisal, ensure_ascii=False, sort_keys=True)
        ),
        fallback=None,
    )


