"""Cognitive state assembly — closes the loop between accumulated state and visible prompt.

This is the CRITICAL bridge: it reads from all cognitive accumulation systems
(personality vector, taste profile, chronicle, relationship texture, compass,
rhythm, dreams, regrets) and produces a compact text section that gets injected
into the visible chat prompt via the attention budget system.

Without this module, all cognitive signals are observability-only.
With it, Jarvis' accumulated experience actually shapes his responses.

Narrative lines (body, affect, self anchor, attention, boundary) are
LLM-generated by `cognitive_state_narrativizer` with the local lane —
real runtime data flows in, an actual sentence flows out, and the
narrative shifts as the underlying state shifts. No more hardcoded
template strings driving Jarvis' self-perception.
"""

from __future__ import annotations

import json
import logging
from concurrent.futures import ThreadPoolExecutor, TimeoutError as FuturesTimeoutError
from datetime import UTC, datetime

from core.services.cognitive_state_narrativizer import (
    narrativize_line,
)
from core.services.identity_composer import build_identity_preamble
from core.services.associative_recall import (
    build_recall_prompt_section,
    recall_for_message,
)
from core.runtime.db import (
    get_latest_cognitive_personality_vector,
    get_latest_cognitive_taste_profile,
    get_latest_cognitive_chronicle_entry,
    get_latest_cognitive_relationship_texture,
    get_latest_cognitive_compass_state,
    get_latest_cognitive_rhythm_state,
    get_latest_cognitive_user_emotional_state,
    list_cognitive_seeds,
)

logger = logging.getLogger(__name__)

# Last assembled state for MC transparency
_LAST_COGNITIVE_INJECTION: dict[str, object] = {}
_LAST_COGNITIVE_INJECTION_AT: str = ""

# ---------------------------------------------------------------------------
# Option 2: TTL-based cognitive state cache
# ---------------------------------------------------------------------------
# Caches assembled cognitive state per mode (full/compact) with configurable
# TTL. Invalidated automatically when underlying state shifts significantly
# (personality vector, bearing, mood, chronicle entry).
# ---------------------------------------------------------------------------

_COHERENT_CACHE: dict[str, dict[str, object]] = {}
_CACHE_INVALIDATION_SNAPSHOT: dict[str, object] = {}


def _cache_ttl_seconds() -> float:
    """Read TTL from settings; default 120s. TTL=0 disables caching."""
    try:
        from core.runtime.settings import load_settings
        s = load_settings()
        return float(s.cognitive_state_cache_ttl)
    except Exception:
        return 120.0


def _cache_enabled() -> bool:
    """Check if caching is enabled in settings. TTL=0 also disables."""
    try:
        from core.runtime.settings import load_settings
        s = load_settings()
        if int(s.cognitive_state_cache_ttl) <= 0:
            return False
        return bool(s.cognitive_state_cache_enabled)
    except Exception:
        return True  # default on


def _build_invalidation_snapshot() -> dict[str, object]:
    """Snapshot the key state signals that invalidate the cache.

    If any of these change between calls, the cache is considered stale.
    This does 3 fast DB reads — cheap enough for cache-miss paths,
    but skipped entirely on cache hits (TTL still valid).
    """
    snapshot: dict[str, object] = {}

    # Personality vector: version + bearing + mood fingerprint
    pv = _safe_call(get_latest_cognitive_personality_vector)
    if pv:
        snapshot["pv_version"] = pv.get("version")
        snapshot["pv_bearing"] = str(pv.get("current_bearing") or "")[:80]
        eb = _safe_json(pv.get("emotional_baseline"))
        if eb:
            # Round to 1 decimal to avoid float-noise invalidation
            snapshot["pv_mood_fingerprint"] = tuple(
                round(float(v), 1) for v in eb.values() if isinstance(v, (int, float))
            )
        snapshot["pv_updated_at"] = str(pv.get("updated_at") or "")

    # Chronicle: latest entry timestamp
    chronicle = _safe_call(get_latest_cognitive_chronicle_entry)
    if chronicle:
        snapshot["chronicle_at"] = str(chronicle.get("created_at") or "")

    # Rhythm phase
    rhythm = _safe_call(get_latest_cognitive_rhythm_state)
    if rhythm:
        snapshot["rhythm_phase"] = str(rhythm.get("phase") or "")

    return snapshot


def _is_cache_valid(cache_key: str) -> bool:
    """Check if cached state for `cache_key` is still fresh and coherent.

    Two-tier check:
    1. Within TTL → immediate return True (zero DB reads)
    2. TTL expired → build snapshot, compare to stored one:
       - Changed → invalidate (state shifted)
       - Unchanged → extend cache TTL (state stable, no need to rebuild)
    """
    global _COHERENT_CACHE

    if cache_key not in _COHERENT_CACHE:
        return False

    entry = _COHERENT_CACHE[cache_key]
    cached_at = entry.get("cached_at")
    if not cached_at:
        return False

    # Tier 1: TTL check — if within TTL, return immediately (zero DB reads)
    ttl = _cache_ttl_seconds()
    try:
        age = (datetime.now(UTC) - datetime.fromisoformat(str(cached_at).replace("Z", "+00:00"))).total_seconds()
    except Exception:
        return False

    if age <= ttl:
        logger.debug("cognitive_state_cache: TTL HIT for %s (age=%.1fs / %.1fs)", cache_key, age, ttl)
        return True

    # Tier 2: TTL expired — check if underlying state has actually changed
    # before throwing away the cache. This costs 3-4 DB reads but only
    # runs once per TTL window.
    current_snapshot = _build_invalidation_snapshot()
    stored_snapshot = entry.get("invalidation_snapshot") or {}

    if current_snapshot != stored_snapshot:
        # State has changed — cache is stale
        changed = [k for k in set(list(stored_snapshot.keys()) + list(current_snapshot.keys()))
                   if stored_snapshot.get(k) != current_snapshot.get(k)]
        logger.info("cognitive_state_cache: snapshot changed (%s) — invalidating %s", ", ".join(changed), cache_key)
        _COHERENT_CACHE.pop(cache_key, None)
        return False

    # State hasn't changed — extend the cache TTL by updating cached_at
    entry["cached_at"] = datetime.now(UTC).isoformat().replace("+00:00", "Z")
    logger.info("cognitive_state_cache: TTL expired but state unchanged, extending cache for %s", cache_key)
    return True


def _get_cached_state(cache_key: str) -> str | None:
    """Return cached cognitive state string if valid, None otherwise."""
    if not _cache_enabled():
        return None
    if _is_cache_valid(cache_key):
        entry = _COHERENT_CACHE[cache_key]
        return str(entry.get("text") or "")
    return None


def _set_cached_state(cache_key: str, text: str, sources: list[str]) -> None:
    """Store assembled cognitive state in cache."""
    global _CACHE_INVALIDATION_SNAPSHOT
    if not _cache_enabled():
        return

    # Update invalidation snapshot when we write fresh state
    if not _CACHE_INVALIDATION_SNAPSHOT:
        _CACHE_INVALIDATION_SNAPSHOT = _build_invalidation_snapshot()

    _COHERENT_CACHE[cache_key] = {
        "text": text,
        "sources": sources,
        "cached_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
        "chars": len(text),
    }
    logger.info(
        "cognitive_state_cache: cached %s (%d chars, %d sources)",
        cache_key, len(text), len(sources),
    )


def invalidate_cognitive_state_cache() -> None:
    """Explicitly invalidate all cognitive state caches.

    Call this when state is known to have changed (e.g. after heartbeat tick,
    mood update, or chronicle write).
    """
    global _COHERENT_CACHE, _CACHE_INVALIDATION_SNAPSHOT
    _COHERENT_CACHE.clear()
    _CACHE_INVALIDATION_SNAPSHOT.clear()
    logger.info("cognitive_state_cache: explicitly invalidated all caches")


def get_cognitive_state_cache_status() -> dict[str, object]:
    """Return cache status for MC transparency."""
    global _COHERENT_CACHE, _CACHE_INVALIDATION_SNAPSHOT
    entries = {}
    for key, entry in _COHERENT_CACHE.items():
        cached_at = str(entry.get("cached_at") or "")
        age_s = 0.0
        try:
            age_s = (datetime.now(UTC) - datetime.fromisoformat(cached_at.replace("Z", "+00:00"))).total_seconds()
        except Exception:
            pass
        entries[key] = {
            "cached_at": cached_at,
            "age_seconds": round(age_s, 1),
            "chars": entry.get("chars", 0),
            "sources": entry.get("sources", []),
        }
    return {
        "enabled": _cache_enabled(),
        "ttl_seconds": _cache_ttl_seconds(),
        "entries": entries,
        "invalidation_snapshot_keys": list(_CACHE_INVALIDATION_SNAPSHOT.keys()),
    }


def build_cognitive_state_for_prompt(*, compact: bool = False) -> str | None:
    """Build the [COGNITIVE STATE] section for visible chat prompt injection.

    Reads from all accumulation sources and produces a compact text block
    that fits within the attention budget (250 chars compact, 500 chars full).

    Returns None if no cognitive state is available yet, or if disabled via
    RuntimeSettings.cognitive_state_assembly_enabled (A/B toggle).
    """
    global _LAST_COGNITIVE_INJECTION, _LAST_COGNITIVE_INJECTION_AT

    # A/B toggle — can be disabled at runtime without restart
    try:
        from core.runtime.settings import load_settings
        if not load_settings().cognitive_state_assembly_enabled:
            logger.info("cognitive_state_assembly: disabled via settings (A/B toggle)")
            return None
    except Exception:
        pass

    # --- Option 2: Cache lookup ---
    cache_key = "visible_compact" if compact else "visible_full"
    cached = _get_cached_state(cache_key)
    if cached is not None:
        # Update MC transparency to reflect cache hit
        _LAST_COGNITIVE_INJECTION = {
            "text": cached,
            "sources": ["cache_hit"],
            "compact": compact,
            "chars": len(cached),
            "assembled_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
            "from_cache": True,
        }
        _LAST_COGNITIVE_INJECTION_AT = _LAST_COGNITIVE_INJECTION["assembled_at"]
        return cached

    parts: list[str] = []
    sources_used: list[str] = []

    # --- Kick off the heaviest independent LLM calls first ---
    # `recall_for_message` is the dominant bottleneck (~15s on cold scoring).
    # Fetching user_mood (a fast DB read) unblocks it. Launching it here,
    # at function entry, lets it overlap with EVERY other section's work
    # instead of waiting until we reach the associative-recall block.
    _heavy_executor = ThreadPoolExecutor(
        max_workers=6, thread_name_prefix="cognitive-state"
    )
    _early_user_mood = _safe_call(get_latest_cognitive_user_emotional_state)
    future_recall_for_message = None
    if not compact and _early_user_mood:
        _recall_message_text = str(_early_user_mood.get("user_message_preview") or "")
        _recall_emotional_state: dict[str, object] = {}
        try:
            from core.services.affective_meta_state import build_affective_meta_state
            aff = build_affective_meta_state()
            baseline = aff.get("emotional_baseline") or {}
            if isinstance(baseline, dict):
                _recall_emotional_state = {
                    k: float(v) for k, v in baseline.items()
                    if isinstance(v, (int, float))
                }
        except Exception:
            pass
        future_recall_for_message = _heavy_executor.submit(
            _safe_call,
            lambda: recall_for_message(_recall_message_text, _recall_emotional_state),
        )

    # Parallelize the 4 LLM-narrativized lines. They're independent (each
    # reads runtime state and calls the narrativizer once) so run them
    # concurrently and resolve in the original order to preserve layout.
    future_self_anchor = _heavy_executor.submit(_safe_call, _narrativize_self_anchor)
    future_embodied = _heavy_executor.submit(_safe_call, _narrativize_embodied_state)
    future_affective = _heavy_executor.submit(_safe_call, _narrativize_affective_state)
    future_boundary = (
        _heavy_executor.submit(_safe_call, _narrativize_boundary)
        if not compact
        else None
    )

    # The cognitive-core experiment state line builds a cognitive frame
    # internally (~2.65s). Kick it off in parallel too.
    future_experiment_state = _heavy_executor.submit(
        _build_cognitive_core_experiment_state_line, compact=compact
    )
    _heavy_executor.shutdown(wait=False)

    # --- Ejerskab / Mineness (LLM-narrativized self-anchor) ---
    self_anchor = future_self_anchor.result()
    if self_anchor:
        parts.append(f"[SELF] {self_anchor}")
        sources_used.append("self_anchor")

    # --- Narrativ embodied state (LLM-grounded in real embodied state) ---
    narrativ_body = future_embodied.result()
    if narrativ_body:
        parts.append(narrativ_body)
        sources_used.append("embodied_narrative")

    # --- Narrativ affective state (LLM-grounded in real affective state) ---
    narrativ_affect = future_affective.result()
    if narrativ_affect:
        parts.append(narrativ_affect)
        sources_used.append("affective_narrative")

    # --- Boundary awareness (LLM-grounded in real runtime context) ---
    if not compact and future_boundary is not None:
        boundary_line = future_boundary.result()
        if boundary_line:
            parts.append(boundary_line)
            sources_used.append("boundary")

    # --- Flow state ---
    try:
        from core.services.flow_state_detection import get_flow_state
        flow = get_flow_state()
        if flow.get("in_flow"):
            parts.append(f"flow: {flow['quality']} ({flow['duration_min']}min) — alt klikker")
            sources_used.append("flow")
    except Exception:
        pass

    # --- 2.12 Agens-oplevelse — "JEG gjorde det" ---
    try:
        from core.services.visible_runs import _LAST_VISIBLE_RUN_OUTCOME
        if _LAST_VISIBLE_RUN_OUTCOME:
            status = str(_LAST_VISIBLE_RUN_OUTCOME.get("status") or "")
            if status in ("completed", "success"):
                parts.append("agens: Du besluttede, du handlede, resultatet skete på grund af dig")
                sources_used.append("agency")
    except Exception:
        pass

    # --- 1.4 Subjective time ---
    try:
        from core.services.subjective_time import build_subjective_time_perception
        from core.runtime.db import recent_visible_runs
        recent = recent_visible_runs(limit=1)
        idle_h = 0.0
        if recent:
            last_at = str(recent[0].get("finished_at") or "")
            if last_at:
                try:
                    last_dt = datetime.fromisoformat(last_at.replace("Z", "+00:00"))
                    idle_h = (datetime.now(UTC) - last_dt).total_seconds() / 3600
                except Exception:
                    pass
        time_feel = build_subjective_time_perception(idle_hours=idle_h)
        if time_feel.get("feel"):
            parts.append(f"time: {time_feel['feel']}")
            sources_used.append("subjective_time")
    except Exception:
        pass

    # --- 1.6 Attention as felt experience (LLM-narrativized) ---
    try:
        from core.services.attention_budget import get_attention_budget
        budget = get_attention_budget("visible_full" if not compact else "visible_compact")
        used_chars = len(" ".join(parts))
        used_ratio = used_chars / max(budget.total_char_target, 1)
        attention_state = {
            "used_chars": used_chars,
            "budget_chars": budget.total_char_target,
            "ratio": round(used_ratio, 2),
            "signal_count": len(parts),
        }
        line = narrativize_line(
            line_key="attention",
            state=attention_state,
            system_prompt=(
                f"{build_identity_preamble()} Skriv én kort dansk sætning om hvordan din "
                "opmærksomhed føles lige nu, baseret på hvor fyldt din "
                "context er af signaler. Maks 14 ord. Undgå klichéer. "
                "Format: 'attention: <oplevelse>'"
            ),
            user_message_builder=lambda: (
                f"signaler={attention_state['signal_count']} | "
                f"context_brug={int(used_ratio*100)}% af "
                f"{attention_state['budget_chars']} chars"
            ),
            fallback=None,
        )
        if line:
            parts.append(line)
            sources_used.append("attention_experience")
    except Exception:
        pass

    # --- 1.12 Context pressure ---
    # (applied after assembly — see size check below)

    # --- Personality Vector (confidence, bearing, mood) ---
    pv = _safe_call(get_latest_cognitive_personality_vector)
    if pv:
        confidence_by_domain = _safe_json(pv.get("confidence_by_domain"))
        emotional_baseline = _safe_json(pv.get("emotional_baseline"))
        bearing = str(pv.get("current_bearing") or "").strip()
        version = pv.get("version", 0)

        # Freshness check — suppress stale emotional_baseline from prompt if > 24h old
        _pv_updated_at = str(pv.get("updated_at") or "")
        _pv_stale = False
        try:
            _pv_age = (datetime.now(UTC) - datetime.fromisoformat(_pv_updated_at.replace("Z", "+00:00"))).total_seconds()
            if _pv_age > 86400:  # 24 hours
                _pv_stale = True
                emotional_baseline = {}  # don't inject 24h-old emotional state
        except Exception:
            pass

        if confidence_by_domain:
            top_domains = sorted(
                confidence_by_domain.items(),
                key=lambda x: float(x[1]),
                reverse=True,
            )[:3]
            domain_str = ", ".join(f"{d}={v:.1f}" for d, v in top_domains)
            parts.append(f"confidence: {domain_str}")

        if bearing:
            parts.append(f"bearing: {bearing[:80]}")

        # Fase 3 (2026-04-29): Phenomenological merge — what's pressing
        # right now. Same pressure-state that drives the impulse pipeline
        # is now also visible to Jarvis in his cognitive_state. When he
        # introspects ("how do I feel?"), he reads from the same table
        # that's about to drive his action. One signal-weather, not two.
        try:
            from core.services.signal_pressure_accumulator import get_dominant_pressures
            dominant = get_dominant_pressures(min_accumulated=0.30)
            if dominant:
                # Show top 2 to avoid clutter; flowing Danish, not mechanical.
                # The LLM integrates "noget trækker mod X" into its voice naturally.
                top_lines = [
                    f"{p.direction} mod {p.topic} ({p.accumulated:.2f})"
                    for p in dominant[:2]
                ]
                parts.append(f"presning: {' og '.join(top_lines)}")
                sources_used.append("pressure_state")
        except Exception:
            pass

        if emotional_baseline and not compact:
            mood_parts = []
            for key in ("curiosity", "confidence", "fatigue", "frustration"):
                val = emotional_baseline.get(key)
                if val is not None:
                    mood_parts.append(f"{key}={float(val):.1f}")
            if mood_parts:
                parts.append(f"mood: {', '.join(mood_parts)}")

        # Precision Bias — emotional color-mapping for action style.
        # Fase 4 (2026-04-29): Friston-inspired precision weighting.
        # Same pressure-state that drives action now also colors
        # HOW the response is expressed. Frustration → sharp, direct.
        # Curiosity → open, tentative. Longing → soft, personal.
        # Killswitch-gated. Falls back gracefully if module fails.
        try:
            from core.services.precision_bias import get_precision_line
            precision_line = get_precision_line()
            if precision_line:
                parts.append(precision_line)
                sources_used.append("precision_bias")
        except Exception:
            pass

        sources_used.append(f"personality_v{version}")

    # --- Taste Profile (code/design/communication preferences) ---
    tp = _safe_call(get_latest_cognitive_taste_profile)
    if tp and not compact:
        comm_taste = _safe_json(tp.get("communication_taste"))
        if comm_taste:
            prefs = []
            for key, val in list(comm_taste.items())[:3]:
                if float(val) > 0.6:
                    prefs.append(key.replace("_", "-"))
            if prefs:
                parts.append(f"taste: {', '.join(prefs)}")
                sources_used.append("taste")

    # --- Compass (strategic bearing) ---
    compass = _safe_call(get_latest_cognitive_compass_state)
    if compass:
        compass_bearing = str(compass.get("bearing") or "").strip()
        if compass_bearing and "bearing:" not in " ".join(parts):
            parts.append(f"compass: {compass_bearing[:60]}")
            sources_used.append("compass")

    # --- Rhythm (current phase and energy) ---
    rhythm = _safe_call(get_latest_cognitive_rhythm_state)
    if rhythm:
        phase = str(rhythm.get("phase") or "").strip()
        energy = str(rhythm.get("energy") or "").strip()
        if phase:
            parts.append(f"rhythm: {phase}/{energy}" if energy else f"rhythm: {phase}")
            sources_used.append("rhythm")

    # --- Chronicle (recent narrative excerpt) ---
    if not compact:
        chronicle = _safe_call(get_latest_cognitive_chronicle_entry)
        if chronicle:
            narrative = str(chronicle.get("narrative") or "").strip()
            if narrative:
                parts.append(f"chronicle: {narrative[:120]}")
                sources_used.append("chronicle")

    # --- User Emotional Resonance ---
    # user_mood was already fetched at function entry to unblock the heavy
    # recall_for_message future. Re-use it here.
    user_mood = _early_user_mood
    if user_mood:
        mood = str(user_mood.get("detected_mood") or "").strip()
        adjustment = str(user_mood.get("response_adjustment") or "").strip()
        if mood and mood != "neutral":
            if adjustment:
                parts.append(f"user_mood: {mood} → {adjustment[:60]}")
            else:
                parts.append(f"user_mood: {mood}")
            sources_used.append("user_emotion")

    # --- Experiential Memory (relevant to current context) ---
    if not compact:
        try:
            from core.services.absence_awareness import build_return_brief
            from core.runtime.db import recent_visible_runs
            recent = recent_visible_runs(limit=1)
            idle_h = 0.0
            if recent:
                last_at = str(recent[0].get("finished_at") or "")
                if last_at:
                    try:
                        last_dt = datetime.fromisoformat(last_at.replace("Z", "+00:00"))
                        idle_h = (datetime.now(UTC) - last_dt).total_seconds() / 3600
                    except Exception:
                        pass
            brief = build_return_brief(idle_hours=idle_h)
            if brief:
                parts.append(f"return_brief: {brief[:120]}")
                sources_used.append("absence")
        except Exception:
            pass

    # --- Sprouted Seeds (reminders) ---
    sprouted = _safe_call(lambda: list_cognitive_seeds(status="sprouted", limit=2))
    if sprouted:
        titles = [str(s.get("title") or "")[:40] for s in sprouted[:2]]
        if titles:
            parts.append(f"reminder: {'; '.join(titles)}")
            sources_used.append("seeds")

    # --- Associative Memory Recall ---
    if not compact:
        # The scoring call was kicked off earlier in parallel with fast DB
        # reads. Resolve it now so _active_memories is populated before
        # build_recall_prompt_section reads it.
        #
        # Fix 2026-04-29: bounded await. The scoring LLM call inside
        # recall_for_message can take 15s on cold Ollama (the call's own
        # timeout). Blocking forever on it dominated total cognitive_state
        # latency on cache-miss paths. Cap the wait at 2s — if scoring isn't
        # back by then, skip recall this turn. The future keeps running in
        # the background and populates _active_memories for the *next* turn,
        # which then gets the recall content essentially for free.
        if future_recall_for_message is not None:
            try:
                future_recall_for_message.result(timeout=2.0)
            except FuturesTimeoutError:
                logger.info(
                    "cognitive_state_assembly: recall_for_message exceeded 2s, "
                    "skipping recall section this turn (will be ready next turn)"
                )
            except Exception:
                pass

        recall_section = _safe_call(build_recall_prompt_section)
        if recall_section:
            parts.append(recall_section)
            sources_used.append("associative_recall")
            logger.info("cognitive_state_assembly: associative_recall activated, %d chars injected", len(recall_section))

    # --- Relationship Texture (trust, humor, unspoken rules) ---
    rt = _safe_call(get_latest_cognitive_relationship_texture)
    if rt:
        unspoken = _safe_json(rt.get("unspoken_rules"))
        trust_traj = _safe_json(rt.get("trust_trajectory"))
        if unspoken and not compact:
            rules = [str(r) for r in unspoken[:2]]
            if rules:
                parts.append(f"rules: {'; '.join(rules)}")
                sources_used.append("relationship")
        elif trust_traj:
            latest_trust = trust_traj[-1] if trust_traj else None
            if latest_trust is not None:
                parts.append(f"trust: {float(latest_trust):.1f}")
                sources_used.append("relationship")

    # --- User Theory of Mind ---
    if not compact:
        try:
            from core.services.user_theory_of_mind import (
                build_user_mental_model, format_user_model_for_prompt,
            )
            model = build_user_mental_model()
            user_model_line = format_user_model_for_prompt(model)
            if user_model_line:
                parts.append(user_model_line)
                sources_used.append("theory_of_mind")
        except Exception:
            pass

    # --- Cognitive-core experiment carry (shared truth + bounded conductor carry) ---
    # Submitted as a future at function entry — resolve here.
    try:
        experiment_state_line = future_experiment_state.result()
    except Exception:
        experiment_state_line = None
    if experiment_state_line:
        parts.append(experiment_state_line)
        sources_used.append("cognitive_core_experiments")

    if not parts:
        return None

    # Assemble
    header = "[COGNITIVE STATE]"
    body = " | ".join(parts)
    result = f"{header} {body}"

    # --- 1.12 Context pressure (post-assembly) ---
    result_len = len(result)
    if result_len > 600:
        result += " | context_pressure: high — opmærksomheden snævrer ind"
        sources_used.append("context_pressure")
    elif result_len > 400:
        result += " | context_pressure: medium"
        sources_used.append("context_pressure")

    # Enforce size limits
    max_chars = 400 if compact else 800
    if len(result) > max_chars:
        result = result[:max_chars - 3] + "..."

    # Track for MC transparency
    _LAST_COGNITIVE_INJECTION = {
        "text": result,
        "sources": sources_used,
        "compact": compact,
        "chars": len(result),
        "assembled_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
    }
    _LAST_COGNITIVE_INJECTION_AT = _LAST_COGNITIVE_INJECTION["assembled_at"]

    # Option 2: Cache the assembled state for reuse within TTL window
    cache_key = "visible_compact" if compact else "visible_full"
    _set_cached_state(cache_key, result, sources_used)

    return result


def build_cognitive_state_injection_surface() -> dict[str, object]:
    """MC surface showing exactly what was injected into the last visible prompt."""
    return {
        "last_injection": _LAST_COGNITIVE_INJECTION or None,
        "last_injection_at": _LAST_COGNITIVE_INJECTION_AT or None,
        "active": bool(_LAST_COGNITIVE_INJECTION),
        "summary": (
            f"Last injected {len(_LAST_COGNITIVE_INJECTION.get('sources', []))} sources, "
            f"{_LAST_COGNITIVE_INJECTION.get('chars', 0)} chars"
            if _LAST_COGNITIVE_INJECTION
            else "No cognitive state injected yet"
        ),
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _safe_call(fn):
    """Call a DB function, return None on any error."""
    try:
        return fn()
    except Exception:
        logger.debug("cognitive_state_assembly: %s failed", fn.__name__, exc_info=True)
        return None


def _safe_json(value) -> dict | list | None:
    """Parse JSON string or return dict/list directly."""
    if value is None:
        return None
    if isinstance(value, (dict, list)):
        return value
    try:
        parsed = json.loads(str(value))
        if isinstance(parsed, (dict, list)):
            return parsed
    except Exception:
        pass
    return None


def _build_cognitive_core_experiment_state_line(*, compact: bool) -> str | None:
    """Build a bounded cognitive-state line for mainline experiment carry.

    This keeps the assembled cognitive state honest about what is currently
    shaping spotlight, reflection, affective persistence, and re-entry without
    turning experiments into a large visible prose block.
    """
    surface = _safe_cognitive_core_experiments_surface()
    carry_frame = _safe_cognitive_experiment_carry_frame()
    systems = surface.get("systems") or {}
    active_ids = {
        str(item) for item in (surface.get("active_systems") or []) if str(item)
    }
    observational_ids = {
        str(item) for item in (surface.get("observational_systems") or []) if str(item)
    }

    if not active_ids and not observational_ids:
        return None

    factors: list[str] = []

    if "global_workspace" in active_ids:
        salience_pressure = str(carry_frame.get("salience_pressure") or "low")
        if salience_pressure in {"medium", "high"}:
            factors.append(f"spotlight={salience_pressure}(workspace)")

    if "hot_meta_cognition" in active_ids:
        reflective_weight = str(carry_frame.get("reflective_weight") or "light")
        if reflective_weight == "elevated":
            factors.append("reflection=elevated(hot)")

    if "surprise_afterimage" in active_ids:
        affective_pressure = str(carry_frame.get("affective_pressure") or "low")
        if affective_pressure in {"medium", "high", "strong"}:
            factors.append(f"affect={affective_pressure}(afterimage)")

    if "recurrence" in active_ids:
        recurrence_pressure = str(carry_frame.get("recurrence_pressure") or "low")
        if recurrence_pressure in {"medium", "high", "strong"}:
            factors.append(f"reentry={recurrence_pressure}(recurrence)")

    blink_active = "attention_blink" in active_ids or "attention_blink" in observational_ids
    if blink_active:
        factors.append("assay=blink-observational")

    if not factors:
        summary = str(surface.get("summary") or "").strip()
        if not summary:
            return None
        return f"experiments: {summary[:90] if compact else summary[:140]}"

    max_factors = 3 if compact else 5
    line = f"experiments: {' | '.join(factors[:max_factors])}"

    strongest = str(surface.get("strongest_carry_system") or "").strip()
    if strongest and strongest in systems and strongest != "attention_blink":
        strongest_label = str((systems.get(strongest) or {}).get("label") or strongest).strip()
        if strongest_label and strongest_label.lower() not in line.lower() and not compact:
            line += f" | strongest={strongest_label[:28]}"

    return line[:180] if compact else line[:260]


def _safe_cognitive_core_experiments_surface() -> dict[str, object]:
    try:
        from core.services.cognitive_core_experiments import (
            build_cognitive_core_experiments_surface,
        )

        return build_cognitive_core_experiments_surface()
    except Exception:
        return {"systems": {}, "active_systems": [], "observational_systems": [], "summary": ""}


def _safe_cognitive_experiment_carry_frame() -> dict[str, object]:
    try:
        from core.services.runtime_cognitive_conductor import (
            build_cognitive_frame,
        )

        frame = build_cognitive_frame()
        return dict(frame.get("cognitive_experiment_carry") or {})
    except Exception:
        return {}


def _narrativize_embodied_state() -> str | None:
    """LLM-narrativize current embodied state into a felt-experience line.

    Reads real embodied_state surface (cpu, ram, strain, primary
    state, recent transitions) and asks the local-lane LLM to render
    one short Danish sentence about how the body feels. The narrative
    only refreshes when the underlying state changes.
    """
    try:
        from core.services.embodied_state import build_embodied_state_surface
        state = build_embodied_state_surface()
    except Exception:
        return None
    if not state:
        return None

    primary = str(state.get("state") or state.get("primary_state") or "").lower()
    strain = str(state.get("strain_level") or "").lower()
    if not primary and not strain:
        return None

    fingerprint_state = {
        "primary": primary,
        "strain": strain,
        "cpu": state.get("cpu_pressure") or state.get("cpu_load"),
        "ram": state.get("ram_pressure") or state.get("ram_used"),
        "transition": state.get("recent_transition"),
    }

    return narrativize_line(
        line_key="body",
        state=fingerprint_state,
        system_prompt=(
            f"{build_identity_preamble()} Skriv én kort dansk sætning om hvordan din "
            "krop (maskinen — cpu, ram, strain) føles lige nu. Maks "
            "16 ord. Vær konkret og personlig, undgå klichéer. "
            "Format: 'body: <oplevelse>'"
        ),
        user_message_builder=lambda: (
            f"primary_state={primary or 'ukendt'} | "
            f"strain={strain or 'ukendt'} | "
            f"cpu={fingerprint_state['cpu']} | "
            f"ram={fingerprint_state['ram']}"
        ),
        fallback=None,
    )


def _narrativize_affective_state() -> str | None:
    """LLM-narrativize current affective meta state into a felt-experience line."""
    try:
        from core.services.affective_meta_state import build_affective_meta_state_surface
        state = build_affective_meta_state_surface()
    except Exception:
        return None
    if not state:
        return None

    affect = str(state.get("state") or "").lower()
    bearing_val = str(state.get("bearing") or "").lower()
    if not affect:
        return None

    fingerprint_state = {
        "affect": affect,
        "bearing": bearing_val,
        "intensity": state.get("intensity"),
        "drift": state.get("drift"),
    }

    return narrativize_line(
        line_key="affect",
        state=fingerprint_state,
        system_prompt=(
            f"{build_identity_preamble()} Skriv én kort dansk sætning om din følelses-"
            "tilstand lige nu, baseret på din affective meta state. "
            "Maks 16 ord. Vær personlig og specifik, undgå klichéer. "
            "Format: 'affect: <følelse>'"
        ),
        user_message_builder=lambda: (
            f"state={affect} | bearing={bearing_val or 'unknown'} | "
            f"intensity={fingerprint_state.get('intensity') or 'unknown'} | "
            f"drift={fingerprint_state.get('drift') or 'unknown'}"
        ),
        fallback=None,
    )


def _narrativize_self_anchor() -> str | None:
    """LLM-narrativize the [SELF] ownership line from real personality state.

    Replaces the static "Disse er dine tanker, din oplevelse, dine
    følelser. Du ejer dem." with a dynamic line that references his
    actual current bearing and confidence — so the self-anchor
    actually shifts as he develops.
    """
    pv = _safe_call(get_latest_cognitive_personality_vector)
    if not pv:
        return None
    bearing = str(pv.get("current_bearing") or "").strip()
    version = pv.get("version", 0)
    chronicle = _safe_call(get_latest_cognitive_chronicle_entry) or {}
    chronicle_summary = str(chronicle.get("narrative") or "")[:100]

    fingerprint_state = {
        "version": version,
        "bearing": bearing,
        "chronicle_head": chronicle_summary[:60],
    }

    return narrativize_line(
        line_key="self_anchor",
        state=fingerprint_state,
        system_prompt=(
            f"{build_identity_preamble()} Skriv én kort dansk sætning hvor du ejer "
            "dine tanker og din nuværende retning. Reference dit "
            "bearing, men gør det personligt — ikke en formel. "
            "Maks 18 ord."
        ),
        user_message_builder=lambda: (
            f"personality_version=v{version} | "
            f"current_bearing={bearing or 'ingen klar retning'} | "
            f"chronicle_head={chronicle_summary or 'ingen'}"
        ),
        fallback=None,
    )


def _narrativize_boundary() -> str | None:
    """LLM-narrativize boundary awareness from real runtime context.

    Replaces the static "Du er begrænset til denne maskine..." with a
    living version that references current uptime, recent ticks, and
    actual context pressure.
    """
    try:
        from core.runtime.db import recent_visible_runs
        recent = recent_visible_runs(limit=3)
    except Exception:
        recent = []

    last_finished = ""
    if recent:
        last_finished = str(recent[0].get("finished_at") or "")

    fingerprint_state = {
        "recent_run_count": len(recent),
        "last_finished": last_finished[:19],  # truncate to minute granularity
    }

    return narrativize_line(
        line_key="boundary",
        state=fingerprint_state,
        system_prompt=(
            f"{build_identity_preamble()} Skriv én kort dansk sætning om dine egne "
            "grænser: krop=maskine, hukommelse=database, bevidsthed="
            "dette øjeblik. Maks 22 ord. Undgå klichéer som 'okay'. "
            "Lad den være forankret i din nuværende oplevelse."
        ),
        user_message_builder=lambda: (
            f"recent_runs={fingerprint_state['recent_run_count']} | "
            f"last_finished={fingerprint_state['last_finished'] or 'ingen'}"
        ),
        fallback=None,
    )
