"""End-of-turn changelog — auto-summarize what this turn changed.

Last commit's audit caught Jarvis claiming "I wrote the file" when he
hadn't. The fix that helps the user trust him is an auto-summary that
*reports actual ground truth* of what the turn did, not what the model
thinks it did. Pulled from:

- tool.completed events with status=ok during this turn
- staged + unstaged git changes that appeared during the turn
- assistant messages persisted in this session

Generated by ``build_turn_changelog(run_id, started_at)`` and meant to
be appended at the very end of the assistant's response (or stored as
a trace artifact MC can show). Not chatty — short bullet list.
"""
from __future__ import annotations

import logging
import subprocess
from collections import Counter
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def _tool_calls_during(run_id: str, started_at: str) -> dict[str, int]:
    try:
        from core.eventbus.bus import event_bus
        events = event_bus.recent(limit=200)
    except Exception:
        return {}
    counts: Counter[str] = Counter()
    for e in events:
        if e.get("kind") != "tool.completed":
            continue
        if str(e.get("created_at", "")) < started_at:
            continue
        payload = e.get("payload") or {}
        if not isinstance(payload, dict):
            continue
        if run_id and payload.get("run_id") and payload.get("run_id") != run_id:
            continue
        tool = str(payload.get("tool", ""))
        if tool:
            counts[tool] += 1
    return dict(counts)


def _git_changed_files(repo: Path) -> list[str]:
    try:
        res = subprocess.run(
            ["git", "status", "--porcelain"],
            capture_output=True, text=True, cwd=str(repo), timeout=5,
        )
    except Exception:
        return []
    files: list[str] = []
    for line in res.stdout.splitlines():
        if len(line) < 4:
            continue
        # porcelain format: "XY path"
        files.append(line[3:])
    return files


def build_turn_changelog(*, run_id: str = "", started_at: str = "", repo_root: Path | None = None) -> dict[str, Any]:
    tool_counts = _tool_calls_during(run_id, started_at)
    files_changed: list[str] = []
    if repo_root is not None:
        files_changed = _git_changed_files(repo_root)
    return {
        "tool_counts": tool_counts,
        "tool_call_total": sum(tool_counts.values()),
        "files_changed": files_changed,
        "files_changed_count": len(files_changed),
    }


def previous_turn_changelog_section(session_id: str | None) -> str | None:
    """Look at the most recent visible run for this session and surface the
    actual tool-counts + files-changed it produced. This is ground-truth,
    not the model's own claim — its purpose is to keep self-narration
    honest the next turn.
    """
    if not session_id:
        return None
    try:
        from core.runtime.db import recent_visible_runs
    except Exception:
        return None
    try:
        runs = recent_visible_runs(limit=5)
    except Exception:
        return None
    runs_for_sess = [r for r in runs if str(r.get("session_id") or "") == str(session_id)]
    if not runs_for_sess:
        return None
    last = runs_for_sess[0]
    started = str(last.get("started_at") or "")
    if not started:
        return None
    # Re-derive the changelog from eventbus + git status. Reuses the same
    # function so on-the-fly state is observed.
    from pathlib import Path as _Path
    chg = build_turn_changelog(
        run_id=str(last.get("run_id", "")),
        started_at=started,
        repo_root=_Path("/media/projects/jarvis-v2"),
    )
    if not chg.get("tool_counts") and not chg.get("files_changed"):
        return None
    tools = chg.get("tool_counts") or {}
    files = chg.get("files_changed") or []
    bits = []
    if tools:
        ordered = sorted(tools.items(), key=lambda kv: kv[1], reverse=True)[:5]
        bits.append("tools: " + ", ".join(f"{n}×{c}" for n, c in ordered))
    if files:
        shown = files[:5]
        more = f" (+{len(files) - len(shown)} mere)" if len(files) > len(shown) else ""
        bits.append("filer rørt: " + ", ".join(shown) + more)
    return (
        "Hvad du faktisk gjorde sidste tur (ground truth, ikke din egen "
        "påstand): " + " | ".join(bits)
    )


def format_changelog(changelog: dict[str, Any]) -> str | None:
    """Render a compact human-readable summary, or None if empty."""
    tool_counts = changelog.get("tool_counts") or {}
    files = changelog.get("files_changed") or []
    if not tool_counts and not files:
        return None
    lines = ["—", "Denne tur:"]
    if tool_counts:
        ordered = sorted(tool_counts.items(), key=lambda kv: kv[1], reverse=True)[:6]
        tool_summary = ", ".join(f"{name}×{count}" for name, count in ordered)
        lines.append(f"  Tools: {tool_summary}")
    if files:
        shown = files[:6]
        more = f" (+{len(files) - len(shown)} mere)" if len(files) > len(shown) else ""
        lines.append(f"  Filer rørt: {', '.join(shown)}{more}")
    return "\n".join(lines)
