from __future__ import annotations

import importlib
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest


@pytest.fixture()
def isolated_runtime(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> SimpleNamespace:
    repo_root = Path(__file__).resolve().parents[1]
    if str(repo_root) not in sys.path:
        sys.path.insert(0, str(repo_root))
    monkeypatch.chdir(repo_root)

    home = tmp_path / "home"
    home.mkdir(parents=True, exist_ok=True)
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("JARVIS_WORKSPACES_DIR", str(tmp_path / "workspaces"))

    module_names = [
        "core.runtime.config",
        "core.runtime.settings",
        "core.runtime.db",
        "core.runtime.bootstrap",
        "core.auth.profiles",
        "core.auth.copilot_oauth",
        "core.auth.openai_oauth",
        "core.runtime.provider_router",
        "core.identity.workspace_bootstrap",
        "core.identity.visible_identity",
        "core.tools.workspace_capabilities",
        "core.services.prompt_contract",
        "core.services.visible_model",
        "core.services.cheap_provider_runtime",
        "core.services.heartbeat_runtime",
        "core.services.candidate_tracking",
        "core.services.non_visible_lane_execution",
        "core.services.reflection_signal_tracking",
        "core.services.temporal_recurrence_signal_tracking",
        "core.services.witness_signal_tracking",
        "core.services.open_loop_signal_tracking",
        "core.services.internal_opposition_signal_tracking",
        "core.services.self_review_signal_tracking",
        "core.services.self_review_record_tracking",
        "core.services.self_review_run_tracking",
        "core.services.self_review_outcome_tracking",
        "core.services.self_review_cadence_signal_tracking",
        "core.services.dream_hypothesis_signal_tracking",
        "core.services.dream_adoption_candidate_tracking",
        "core.services.dream_influence_proposal_tracking",
        "core.services.self_authored_prompt_proposal_tracking",
        "core.services.user_understanding_signal_tracking",
        "core.services.remembered_fact_signal_tracking",
        "core.services.private_inner_note_signal_tracking",
        "core.services.private_initiative_tension_signal_tracking",
        "core.services.private_inner_interplay_signal_tracking",
        "core.services.private_state_snapshot_tracking",
        "core.services.diary_synthesis_signal_tracking",
        "core.services.private_temporal_curiosity_state_tracking",
        "core.services.inner_visible_support_signal_tracking",
        "core.services.regulation_homeostasis_signal_tracking",
        "core.services.relation_state_signal_tracking",
        "core.services.relation_continuity_signal_tracking",
        "core.services.meaning_significance_signal_tracking",
        "core.services.temperament_tendency_signal_tracking",
        "core.services.self_narrative_continuity_signal_tracking",
        "core.services.metabolism_state_signal_tracking",
        "core.services.release_marker_signal_tracking",
        "core.services.consolidation_target_signal_tracking",
        "core.services.selective_forgetting_candidate_tracking",
        "core.services.attachment_topology_signal_tracking",
        "core.services.loyalty_gradient_signal_tracking",
        "core.services.autonomy_pressure_signal_tracking",
        "core.services.proactive_loop_lifecycle_tracking",
        "core.services.proactive_question_gate_tracking",
        "core.services.tiny_webchat_execution_pilot",
        "core.services.self_narrative_self_model_review_bridge",
        "core.services.executive_contradiction_signal_tracking",
        "core.services.private_temporal_promotion_signal_tracking",
        "core.services.chronicle_consolidation_signal_tracking",
        "core.services.chronicle_consolidation_brief_tracking",
        "core.services.chronicle_consolidation_proposal_tracking",
        "core.services.emergent_signal_tracking",
        "core.services.user_md_update_proposal_tracking",
        "core.services.memory_md_update_proposal_tracking",
        "core.services.selfhood_proposal_tracking",
        "core.services.open_loop_closure_proposal_tracking",
        "core.services.internal_cadence",
        "core.services.embodied_state",
        "core.services.affective_meta_state",
        "core.services.experiential_runtime_context",
        "core.services.epistemic_runtime_state",
        "core.services.subagent_ecology",
        "core.services.council_runtime",
        "core.services.adaptive_planner_runtime",
        "core.services.adaptive_reasoning_runtime",
        "core.services.guided_learning_runtime",
        "core.services.adaptive_learning_runtime",
        "core.services.dream_influence_runtime",
        "core.services.self_system_code_awareness",
        "core.services.bounded_repo_tools_runtime",
        "core.services.bounded_action_continuity_runtime",
        "core.services.bounded_mutation_intent_runtime",
        "core.services.tool_intent_approval_runtime",
        "core.services.tool_intent_runtime",
        "core.services.loop_runtime",
        "core.services.idle_consolidation",
        "core.services.dream_articulation",
        "core.services.prompt_evolution_runtime",
        "core.services.self_critique_runtime",
        "core.services.runtime_self_model",
        "apps.api.jarvis_api.routes.mission_control",
    ]
    modules: dict[str, object] = {}
    for name in module_names:
        module = importlib.import_module(name)
        modules[name] = importlib.reload(module)

    runtime_bootstrap = modules["core.runtime.bootstrap"]
    runtime_db = modules["core.runtime.db"]
    workspace_bootstrap = modules["core.identity.workspace_bootstrap"]

    runtime_bootstrap.ensure_runtime_dirs()
    runtime_db.init_db()
    workspace_bootstrap.ensure_default_workspace()

    return SimpleNamespace(
        config=modules["core.runtime.config"],
        settings=modules["core.runtime.settings"],
        db=runtime_db,
        bootstrap=runtime_bootstrap,
        auth_profiles=modules["core.auth.profiles"],
        copilot_oauth=modules["core.auth.copilot_oauth"],
        openai_oauth=modules["core.auth.openai_oauth"],
        provider_router=modules["core.runtime.provider_router"],
        runtime_surface_cache=importlib.import_module(
            "core.services.runtime_surface_cache"
        ),
        workspace_bootstrap=workspace_bootstrap,
        visible_identity=modules["core.identity.visible_identity"],
        workspace_capabilities=modules["core.tools.workspace_capabilities"],
        prompt_contract=modules["core.services.prompt_contract"],
        visible_model=modules["core.services.visible_model"],
        cheap_provider_runtime=modules[
            "core.services.cheap_provider_runtime"
        ],
        heartbeat_runtime=modules["core.services.heartbeat_runtime"],
        candidate_tracking=modules["core.services.candidate_tracking"],
        non_visible_lane_execution=modules[
            "core.services.non_visible_lane_execution"
        ],
        reflection_tracking=modules[
            "core.services.reflection_signal_tracking"
        ],
        temporal_recurrence_tracking=modules[
            "core.services.temporal_recurrence_signal_tracking"
        ],
        witness_tracking=modules[
            "core.services.witness_signal_tracking"
        ],
        open_loop_tracking=modules[
            "core.services.open_loop_signal_tracking"
        ],
        internal_opposition_tracking=modules[
            "core.services.internal_opposition_signal_tracking"
        ],
        self_review_tracking=modules[
            "core.services.self_review_signal_tracking"
        ],
        self_review_record_tracking=modules[
            "core.services.self_review_record_tracking"
        ],
        self_review_run_tracking=modules[
            "core.services.self_review_run_tracking"
        ],
        self_review_outcome_tracking=modules[
            "core.services.self_review_outcome_tracking"
        ],
        self_review_cadence_tracking=modules[
            "core.services.self_review_cadence_signal_tracking"
        ],
        dream_hypothesis_tracking=modules[
            "core.services.dream_hypothesis_signal_tracking"
        ],
        dream_adoption_candidate_tracking=modules[
            "core.services.dream_adoption_candidate_tracking"
        ],
        dream_influence_proposal_tracking=modules[
            "core.services.dream_influence_proposal_tracking"
        ],
        self_authored_prompt_proposal_tracking=modules[
            "core.services.self_authored_prompt_proposal_tracking"
        ],
        user_understanding_signal_tracking=modules[
            "core.services.user_understanding_signal_tracking"
        ],
        remembered_fact_signal_tracking=modules[
            "core.services.remembered_fact_signal_tracking"
        ],
        private_inner_note_signal_tracking=modules[
            "core.services.private_inner_note_signal_tracking"
        ],
        private_initiative_tension_signal_tracking=modules[
            "core.services.private_initiative_tension_signal_tracking"
        ],
        private_inner_interplay_signal_tracking=modules[
            "core.services.private_inner_interplay_signal_tracking"
        ],
        private_state_snapshot_tracking=modules[
            "core.services.private_state_snapshot_tracking"
        ],
        diary_synthesis_signal_tracking=modules[
            "core.services.diary_synthesis_signal_tracking"
        ],
        private_temporal_curiosity_state_tracking=modules[
            "core.services.private_temporal_curiosity_state_tracking"
        ],
        inner_visible_support_signal_tracking=modules[
            "core.services.inner_visible_support_signal_tracking"
        ],
        regulation_homeostasis_signal_tracking=modules[
            "core.services.regulation_homeostasis_signal_tracking"
        ],
        relation_state_signal_tracking=modules[
            "core.services.relation_state_signal_tracking"
        ],
        relation_continuity_signal_tracking=modules[
            "core.services.relation_continuity_signal_tracking"
        ],
        meaning_significance_signal_tracking=modules[
            "core.services.meaning_significance_signal_tracking"
        ],
        temperament_tendency_signal_tracking=modules[
            "core.services.temperament_tendency_signal_tracking"
        ],
        self_narrative_continuity_signal_tracking=modules[
            "core.services.self_narrative_continuity_signal_tracking"
        ],
        metabolism_state_signal_tracking=modules[
            "core.services.metabolism_state_signal_tracking"
        ],
        release_marker_signal_tracking=modules[
            "core.services.release_marker_signal_tracking"
        ],
        consolidation_target_signal_tracking=modules[
            "core.services.consolidation_target_signal_tracking"
        ],
        selective_forgetting_candidate_tracking=modules[
            "core.services.selective_forgetting_candidate_tracking"
        ],
        attachment_topology_signal_tracking=modules[
            "core.services.attachment_topology_signal_tracking"
        ],
        loyalty_gradient_signal_tracking=modules[
            "core.services.loyalty_gradient_signal_tracking"
        ],
        autonomy_pressure_signal_tracking=modules[
            "core.services.autonomy_pressure_signal_tracking"
        ],
        proactive_loop_lifecycle_tracking=modules[
            "core.services.proactive_loop_lifecycle_tracking"
        ],
        proactive_question_gate_tracking=modules[
            "core.services.proactive_question_gate_tracking"
        ],
        tiny_webchat_execution_pilot=modules[
            "core.services.tiny_webchat_execution_pilot"
        ],
        self_narrative_self_model_review_bridge=modules[
            "core.services.self_narrative_self_model_review_bridge"
        ],
        executive_contradiction_signal_tracking=modules[
            "core.services.executive_contradiction_signal_tracking"
        ],
        private_temporal_promotion_signal_tracking=modules[
            "core.services.private_temporal_promotion_signal_tracking"
        ],
        chronicle_consolidation_signal_tracking=modules[
            "core.services.chronicle_consolidation_signal_tracking"
        ],
        chronicle_consolidation_brief_tracking=modules[
            "core.services.chronicle_consolidation_brief_tracking"
        ],
        chronicle_consolidation_proposal_tracking=modules[
            "core.services.chronicle_consolidation_proposal_tracking"
        ],
        emergent_signal_tracking=modules[
            "core.services.emergent_signal_tracking"
        ],
        user_md_update_proposal_tracking=modules[
            "core.services.user_md_update_proposal_tracking"
        ],
        memory_md_update_proposal_tracking=modules[
            "core.services.memory_md_update_proposal_tracking"
        ],
        selfhood_proposal_tracking=modules[
            "core.services.selfhood_proposal_tracking"
        ],
        open_loop_closure_proposal_tracking=modules[
            "core.services.open_loop_closure_proposal_tracking"
        ],
        internal_cadence=modules[
            "core.services.internal_cadence"
        ],
        embodied_state=modules[
            "core.services.embodied_state"
        ],
        affective_meta_state=modules[
            "core.services.affective_meta_state"
        ],
        experiential_runtime_context=modules[
            "core.services.experiential_runtime_context"
        ],
        epistemic_runtime_state=modules[
            "core.services.epistemic_runtime_state"
        ],
        subagent_ecology=modules[
            "core.services.subagent_ecology"
        ],
        council_runtime=modules[
            "core.services.council_runtime"
        ],
        adaptive_planner_runtime=modules[
            "core.services.adaptive_planner_runtime"
        ],
        adaptive_reasoning_runtime=modules[
            "core.services.adaptive_reasoning_runtime"
        ],
        guided_learning_runtime=modules[
            "core.services.guided_learning_runtime"
        ],
        adaptive_learning_runtime=modules[
            "core.services.adaptive_learning_runtime"
        ],
        self_system_code_awareness=modules[
            "core.services.self_system_code_awareness"
        ],
        bounded_action_continuity_runtime=modules[
            "core.services.bounded_action_continuity_runtime"
        ],
        bounded_mutation_intent_runtime=modules[
            "core.services.bounded_mutation_intent_runtime"
        ],
        bounded_repo_tools_runtime=modules[
            "core.services.bounded_repo_tools_runtime"
        ],
        tool_intent_approval_runtime=modules[
            "core.services.tool_intent_approval_runtime"
        ],
        tool_intent_runtime=modules[
            "core.services.tool_intent_runtime"
        ],
        dream_influence_runtime=modules[
            "core.services.dream_influence_runtime"
        ],
        loop_runtime=modules[
            "core.services.loop_runtime"
        ],
        idle_consolidation=modules[
            "core.services.idle_consolidation"
        ],
        dream_articulation=modules[
            "core.services.dream_articulation"
        ],
        prompt_evolution_runtime=modules[
            "core.services.prompt_evolution_runtime"
        ],
        self_critique_runtime=modules[
            "core.services.self_critique_runtime"
        ],
        runtime_self_model=modules[
            "core.services.runtime_self_model"
        ],
        mission_control=modules["apps.api.jarvis_api.routes.mission_control"],
    )
