from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from core.services.attributed_git_commit import commit_with_attribution
from core.services.commit_attribution import CommitAttribution
from scripts.install_git_hooks import REFERENCE_HOOK_IMPL, check_installation
from scripts.validate_commit_attribution import (
    commits_in_enforced_range,
    validate_message_file,
    validate_range,
)


def _git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True,
        text=True,
        check=check,
    )


@pytest.fixture
def git_repo(tmp_path: Path) -> Path:
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "test@example.com")
    _git(tmp_path, "config", "user.name", "Test User")
    (tmp_path / "file.txt").write_text("zero\n")
    _git(tmp_path, "add", "file.txt")
    _git(tmp_path, "commit", "-qm", "initial")
    return tmp_path


def _commit_raw(repo: Path, message: str, content: str) -> str:
    (repo / "file.txt").write_text(content)
    _git(repo, "add", "file.txt")
    _git(repo, "commit", "-qm", message)
    return _git(repo, "rev-parse", "HEAD").stdout.strip()


def _commit_attributed(repo: Path, run_id: str, content: str) -> str:
    (repo / "file.txt").write_text(content)
    _git(repo, "add", "file.txt")
    result = commit_with_attribution(
        repo=repo,
        message="fix: attributed",
        attribution=CommitAttribution(
            actor="codex",
            actor_type="agent",
            run_id=run_id,
            session_id="none",
            origin="delegated",
            approved_by="bjorn",
        ),
        paths=("file.txt",),
    )
    assert result.returncode == 0, result.stderr
    return result.sha


def test_message_file_reports_all_missing_fields(tmp_path: Path) -> None:
    path = tmp_path / "COMMIT_EDITMSG"
    path.write_text("fix: missing trailers\n")

    errors = validate_message_file(path)

    assert len(errors) == 6
    assert any("Actor" in error for error in errors)
    assert any("Approved-By" in error for error in errors)


def test_range_returns_only_pushed_commits_after_baseline(git_repo: Path) -> None:
    baseline = _git(git_repo, "rev-parse", "HEAD").stdout.strip()
    legacy = _commit_raw(git_repo, "legacy after baseline", "one\n")
    attributed = _commit_attributed(git_repo, "task-range", "two\n")

    commits = commits_in_enforced_range(
        git_repo, baseline, baseline, "HEAD"
    )

    assert commits == (legacy, attributed)
    failures = validate_range(git_repo, commits)
    assert set(failures) == {legacy}
    assert any("Actor" in error for error in failures[legacy])


def test_range_intersects_remote_delta_with_baseline(git_repo: Path) -> None:
    baseline = _git(git_repo, "rev-parse", "HEAD").stdout.strip()
    before_push = _commit_attributed(git_repo, "task-before", "one\n")
    pushed = _commit_attributed(git_repo, "task-pushed", "two\n")

    commits = commits_in_enforced_range(
        git_repo, baseline, before_push, pushed
    )

    assert commits == (pushed,)


def test_range_fails_when_baseline_is_not_ancestor(git_repo: Path) -> None:
    baseline = _git(git_repo, "rev-parse", "HEAD").stdout.strip()
    _git(git_repo, "checkout", "-qb", "other")
    unrelated = _commit_raw(git_repo, "other root", "other\n")
    _git(git_repo, "checkout", "--orphan", "orphan")
    _git(git_repo, "rm", "-qf", "file.txt")
    (git_repo / "orphan.txt").write_text("orphan\n")
    _git(git_repo, "add", "orphan.txt")
    _git(git_repo, "commit", "-qm", "orphan")

    with pytest.raises(ValueError, match="not an ancestor"):
        commits_in_enforced_range(git_repo, baseline, "", "HEAD")

    assert unrelated


def test_installation_check_rejects_plain_hook_files(git_repo: Path) -> None:
    hook_dir = Path(_git(git_repo, "rev-parse", "--git-path", "hooks").stdout.strip())
    if not hook_dir.is_absolute():
        hook_dir = git_repo / hook_dir
    for name in (
        "pre-commit", "commit-msg", "pre-push", "pre-rebase",
        "reference-transaction",
    ):
        path = hook_dir / name
        path.write_text("#!/bin/sh\nexit 0\n")
        path.chmod(0o755)

    errors = check_installation(git_repo)

    assert len(errors) == 5
    assert all("not managed" in error for error in errors)


def test_installation_check_accepts_active_pre_commit_hooks(git_repo: Path) -> None:
    hook_dir = Path(_git(git_repo, "rev-parse", "--git-path", "hooks").stdout.strip())
    if not hook_dir.is_absolute():
        hook_dir = git_repo / hook_dir
    marker = "# File generated by pre-commit: https://pre-commit.com\n"
    for name in ("pre-commit", "commit-msg", "pre-push", "pre-rebase"):
        path = hook_dir / name
        path.write_text("#!/bin/sh\n" + marker + "exit 0\n")
        path.chmod(0o755)
    reference = hook_dir / "reference-transaction"
    reference.write_text(
        "#!/bin/sh\n# Managed by jarvis commit attribution\nexit 0\n"
    )
    reference.chmod(0o755)
    implementation = hook_dir / REFERENCE_HOOK_IMPL
    implementation.write_text("#!/usr/bin/env python3\n")
    implementation.chmod(0o755)

    assert check_installation(git_repo) == ()


def test_installation_check_rejects_missing_reference_implementation(
    git_repo: Path,
) -> None:
    hook_dir = Path(
        _git(git_repo, "rev-parse", "--git-path", "hooks").stdout.strip()
    )
    if not hook_dir.is_absolute():
        hook_dir = git_repo / hook_dir
    marker = "# File generated by pre-commit: https://pre-commit.com\n"
    for name in ("pre-commit", "commit-msg", "pre-push", "pre-rebase"):
        path = hook_dir / name
        path.write_text("#!/bin/sh\n" + marker + "exit 0\n")
        path.chmod(0o755)
    reference = hook_dir / "reference-transaction"
    reference.write_text(
        "#!/bin/sh\n# Managed by jarvis commit attribution\nexit 0\n"
    )
    reference.chmod(0o755)

    errors = check_installation(git_repo)

    assert len(errors) == 1
    assert "implementation is missing" in errors[0]
