#!/usr/bin/env python3
"""Install or verify the required pre-commit managed Git hooks."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


REQUIRED_HOOKS = ("pre-commit", "commit-msg", "pre-push")
PRE_COMMIT_MARKER = "File generated by pre-commit"


def _hook_path(repo: Path, hook: str) -> Path:
    result = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--git-path", f"hooks/{hook}"],
        capture_output=True,
        text=True,
        timeout=5,
    )
    if result.returncode != 0:
        raise ValueError((result.stderr or "not a Git repository").strip())
    path = Path(result.stdout.strip())
    return path if path.is_absolute() else repo / path


def check_installation(repo: Path) -> tuple[str, ...]:
    """Return one error for every missing or inactive required hook."""

    errors: list[str] = []
    root = Path(repo).resolve()
    for hook in REQUIRED_HOOKS:
        try:
            path = _hook_path(root, hook)
        except ValueError as exc:
            return (str(exc),)
        if not path.is_file():
            errors.append(f"{hook}: hook is missing at {path}")
            continue
        if not os.access(path, os.X_OK):
            errors.append(f"{hook}: hook is not executable at {path}")
            continue
        try:
            content = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            errors.append(f"{hook}: cannot read hook: {exc}")
            continue
        if PRE_COMMIT_MARKER not in content:
            errors.append(f"{hook}: hook is not managed by pre-commit")
    return tuple(errors)


def _local_hooks_path_values(repo: Path) -> tuple[str, ...]:
    result = subprocess.run(
        [
            "git", "-C", str(repo), "config", "--local", "--get-all",
            "core.hooksPath",
        ],
        capture_output=True,
        text=True,
        timeout=5,
    )
    if result.returncode not in (0, 1):
        return ()
    return tuple(line for line in result.stdout.splitlines() if line)


def _is_default_hooks_path(repo: Path, configured: tuple[str, ...]) -> bool:
    if not configured:
        return False
    common = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--git-common-dir"],
        capture_output=True,
        text=True,
        timeout=5,
    )
    if common.returncode != 0:
        return False
    common_dir = Path(common.stdout.strip())
    if not common_dir.is_absolute():
        common_dir = repo / common_dir
    default = (common_dir / "hooks").resolve()
    return all(
        (Path(value) if Path(value).is_absolute() else repo / value).resolve()
        == default
        for value in configured
    )


def install(repo: Path) -> int:
    root = Path(repo).resolve()
    command = [sys.executable, "-m", "pre_commit", "install"]
    for hook in REQUIRED_HOOKS:
        command.extend(["--hook-type", hook])
    configured = _local_hooks_path_values(root)
    temporarily_unset = _is_default_hooks_path(root, configured)
    if temporarily_unset:
        unset = subprocess.run(
            [
                "git", "-C", str(root), "config", "--local", "--unset-all",
                "core.hooksPath",
            ],
            capture_output=True,
            text=True,
        )
        if unset.returncode != 0:
            return unset.returncode
    result_code = 1
    restore_code = 0
    try:
        result_code = subprocess.run(command, cwd=root, text=True).returncode
    finally:
        if temporarily_unset:
            for value in configured:
                restored = subprocess.run(
                    [
                        "git", "-C", str(root), "config", "--local", "--add",
                        "core.hooksPath", value,
                    ],
                    capture_output=True,
                    text=True,
                )
                if restored.returncode != 0:
                    restore_code = restored.returncode
    return restore_code or result_code


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = args.repo.resolve()
    if not args.check and install(root) != 0:
        return 1
    errors = check_installation(root)
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    print("commit attribution hooks: active (pre-commit, commit-msg, pre-push)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
